# 451 — Locus-Level Methylation–Expression Characterization

## Objective

Characterize locus-level DNA-methylation–gene-expression relationships associated
with the frozen tumor-side methylation context of the three Phase 4 cross-system
consensus transcriptomic programs in the TCGA primary-tumor cohort.

The analysis integrates frozen TCGA DNA-methylation and RNA-seq representations
from Phase 2 with the frozen tumor methylation-component context preserved through
Phase 4.

The objective is to determine whether strongly contributing CpG loci from the
relevant frozen methylation components show reproducible associations with
expression of defensibly annotated genes while preserving lineage structure,
platform boundaries, upstream limitations, and explicit separation between
statistical association and biological mechanism.

Inverse promoter-associated methylation–expression relationships are interpreted
as compatible with an epigenetic regulatory hypothesis. They do not establish
methylation-mediated transcriptional repression or biological causality.

## Frozen upstream inputs

Notebook 451 operates on frozen upstream objects:

- the TCGA primary-tumor multi-omic cohort and exact case-level sample mapping
  from notebook 203;
- the frozen TMM-logCPM RNA-seq representation generated in notebook 205;
- the frozen HM450, HM27, and shared HM27/HM450 DNA-methylation
  representations from notebook 203;
- the frozen methylation probe mapping from notebook 203;
- the frozen methylation ICA probe loadings from notebook 205;
- the three frozen Phase 4 consensus transcriptomic programs and their
  tumor-side methylation-component context; and
- frozen tumor-side confounder covariates from notebook 204.

Upstream cohort membership, sample identity, RNA-seq normalization, methylation
QC, methylation-component identities, component orientations, consensus-program
identities, and program definitions are not recomputed or modified on the basis
of locus-level results.

## Frozen program-context boundary

Notebook 451 is restricted to the tumor-side methylation components already
linked to the three frozen consensus transcriptomic programs:

- `CONSENSUS_TX_01` — `METH_IC128`;
- `CONSENSUS_TX_02` — `METH_IC050`; and
- `CONSENSUS_TX_03` — `METH_IC169` and `METH_IC128`.

Because `METH_IC128` occurs in more than one consensus-program context, statistical
inference is performed on unique CpG–gene units rather than duplicated by program
membership.

Consensus-program and methylation-component memberships are preserved as
downstream contextual annotations.

No locus-level result may rescue, exclude, reweight, rename, reorient, or redefine
a frozen consensus program or its upstream tumor methylation context.

## Locus and annotation boundary

The primary locus universe is defined from the strongest signed loading tails of
the relevant frozen methylation components before methylation–expression
association results are inspected.

For each unique relevant methylation component, the primary locus rule retains:

- the 50 most negative-loading CpGs; and
- the 50 most positive-loading CpGs.

This reuses the pre-existing loading-tail convention established upstream rather
than selecting a new threshold from notebook-451 association results.

CpGs shared across methylation components are retained once as loci while
preserving every applicable component and consensus-program membership.

Biological CpG-to-gene and regulatory-context annotation must come from a
versioned, provenance-tracked, frozen annotation authority before inferential
testing begins.

CpG-to-gene mappings are not selected, rescued, or reassigned according to
observed expression associations, cancer relevance, pathway membership,
druggability, or expected biological interpretation.

## Platform and expression boundary

HM450 is the primary methylation platform for locus-level inference because the
relevant methylation-component discovery was performed in the frozen HM450
analysis space and HM450 provides the larger platform-specific tumor cohort.

HM27 is treated as a prespecified platform-sensitivity layer where locus and
lineage coverage permit evaluation.

HM27 and HM450 samples are not naively pooled into a single primary regression
model.

Gene expression is taken directly from the frozen Phase 2 TMM-logCPM
representation. Notebook 451 does not refit expression filtering or
normalization.

Primary methylation inference uses the M-value transformation convention already
established upstream. Beta values remain available for descriptive interpretation.

## Lineage-aware analytical boundary

Cancer lineage is treated as a required structural component of the analysis.

The primary statistical unit is the unique annotated:

`CpG × gene`

pair.

Primary CpG–gene models are restricted to TCGA projects satisfying prespecified
complete-case and within-project variation requirements.

The primary model is:

`gene_expression ~ CpG_methylation + C(project_id)`

with heteroskedasticity-consistent HC3 uncertainty.

Within-project estimates and leave-one-project-out analyses characterize
directional consistency, lineage dependence, and sensitivity to individual
projects for primary FDR-supported associations.

A pooled association alone is not sufficient to establish cross-project
recurrence.

Cross-project recurrence additionally requires prespecified directional support
across eligible projects and leave-one-project-out stability.

Lineage-aware recurrence describes reproducibility of an association across
eligible TCGA projects. It does not establish biological universality across
cancer types.

## Confounding, multiplicity, and sensitivity analyses

The primary model adjusts for TCGA project while preserving the frozen primary
estimand and maximum eligible HM450 cohort.

Prespecified sensitivity analyses evaluate, where applicable:

- tumor purity;
- proliferation;
- leukocyte fraction for loci belonging to `METH_IC128`; and
- HM27 platform consistency.

The additional cellular-composition sensitivity for `METH_IC128` is motivated by
a frozen upstream interpretive limitation and is not activated according to
notebook-451 results.

Sensitivity analyses characterize stability of primary associations and cannot
rescue associations that fail the primary inferential framework.

Multiplicity is controlled using Benjamini–Hochberg FDR across the complete
frozen unique CpG–gene primary hypothesis family.

FDR families are not subdivided post hoc by consensus program, methylation
component, regulatory annotation, association direction, gene class, or TCGA
project.

## Interpretation boundary

A negative methylation coefficient indicates that higher methylation at the CpG
is associated with lower expression of the annotated gene.

When such a relationship occurs at a promoter-associated locus it may be
described as an inverse promoter-associated methylation–expression relationship
compatible with an epigenetic regulatory hypothesis.

It does not establish:

- promoter silencing;
- methylation-mediated repression;
- a causal regulatory interaction;
- a mechanism of drug resistance;
- a validated biomarker;
- a validated therapeutic target; or
- therapeutic reversibility.

Positive, inverse, heterogeneous, lineage-restricted, technically limited, or
null results are all valid scientific outcomes.

## Scope and methodological boundary

Notebook 451 does not:

- redefine or reoptimize consensus programs;
- refit methylation or transcriptomic latent components;
- assign resistant or sensitive labels to TCGA tumors;
- select loci or genes using pharmacogenomic phenotype;
- infer causal regulation from methylation–expression association;
- choose CpG-to-gene mappings according to association results;
- pool HM27 and HM450 naïvely;
- treat HM27 as independent external biological validation;
- use sensitivity analyses to redefine primary significance;
- promote individual genes as validated targets; or
- use downstream functional, pharmacogenomic, perturbational, or therapeutic
  evidence to select locus-level associations.

The resulting CpG–gene relationships constitute secondary locus-level molecular
context for the frozen consensus programs.

## Expected outputs

Notebook 451 will produce reproducible locus-level characterization under:

`data/processed/secondary_characterization/`

The analysis will preserve:

- the deterministic strong-loading CpG universe and CpG–gene annotation
  eligibility;
- the complete frozen primary CpG–gene association family;
- lineage-aware recurrence characterization;
- prespecified sensitivity evidence;
- promoter/regulatory-context annotation;
- consensus-program and methylation-component context; and
- explicit negative, heterogeneous, and technically limited results.

Only downstream-consumable artifacts justified by the completed analysis will be
persisted and registered. Intermediate diagnostic objects remain reproducible
within the notebook unless separate persistence is required for downstream
provenance or reuse.

In [1]:
# =============================================================================
# Imports
# =============================================================================

import json

import h5py
import numpy as np
import pandas as pd
import statsmodels.api as sm

from pancancer_epigenetics.utils.paths import Paths, project_relative_path
from pancancer_epigenetics.utils.file_checks import calculate_sha256
from pancancer_epigenetics.utils.registry import (
    load_json_registry,
    register_json_entry,
)

In [2]:
# =============================================================================
# Resolve frozen upstream artifact paths
# =============================================================================

UPSTREAM_ARTIFACT_IDS = (
    "phase2.203.final_sample_mapping",
    "phase2.203.final_hm27_methylation_betas",
    "phase2.203.final_hm450_methylation_betas",
    "phase2.203.final_shared_methylation_betas",
    "phase2.203.final_probe_mapping",
    "phase2.204.confounder_covariates",
    "phase2.205.rna_program_discovery_expression",
    "phase2.205.methylation_candidate_probe_loadings",
    "phase4.401.consensus_transcriptomic_program_catalog",
    "phase4.401.consensus_tumor_arm_context",
)

with Paths.artifact_registry.open("r", encoding="utf-8") as handle:
    artifact_registry = json.load(handle)

upstream_artifact_paths = {
    artifact_id: (
        Paths.root
        / artifact_registry["artifacts"][artifact_id]["path"]
    )
    for artifact_id in UPSTREAM_ARTIFACT_IDS
}

for artifact_id, path in upstream_artifact_paths.items():
    print(f"{artifact_id}: {project_relative_path(path)}")

phase2.203.final_sample_mapping: data/interim/metadata/tcga_primary_tumor_multiomic_final_case_level_sample_mapping.csv
phase2.203.final_hm27_methylation_betas: data/interim/methylation/tcga_primary_tumor_methylation_hm27_final_case_level_beta_values.npy
phase2.203.final_hm450_methylation_betas: data/interim/methylation/tcga_primary_tumor_methylation_hm450_final_case_level_beta_values.npy
phase2.203.final_shared_methylation_betas: data/interim/methylation/tcga_primary_tumor_methylation_shared_hm27_hm450_final_case_level_beta_values.npy
phase2.203.final_probe_mapping: data/interim/metadata/tcga_primary_tumor_methylation_final_probe_mapping.csv
phase2.204.confounder_covariates: data/interim/metadata/tcga_primary_tumor_multiomic_confounder_covariates.csv
phase2.205.rna_program_discovery_expression: data/interim/expression/tcga_primary_tumor_rnaseq_program_discovery_tmm_logcpm.h5
phase2.205.methylation_candidate_probe_loadings: data/processed/tumor_programs/tcga_primary_tumor_hm450_ica_can

In [3]:
# =============================================================================
# Validate frozen upstream input contract
# =============================================================================

upstream_input_contract = []

for artifact_id, path in upstream_artifact_paths.items():
    entry = artifact_registry["artifacts"][artifact_id]

    upstream_input_contract.append(
        {
            "artifact_id": artifact_id,
            "status": entry["status"],
            "exists": path.is_file(),
        }
    )

upstream_input_contract = pd.DataFrame(upstream_input_contract)

print(
    "All inputs frozen:",
    bool(upstream_input_contract["status"].eq("frozen").all()),
)
print(
    "All input files present:",
    bool(upstream_input_contract["exists"].all()),
)

upstream_input_contract

All inputs frozen: True
All input files present: True


,artifact_id,status,exists
0,phase2.203.final_sample_mapping,frozen,True
1,phase2.203.final_hm27_methylation_betas,frozen,True
2,phase2.203.final_hm450_methylation_betas,frozen,True
3,phase2.203.final_shared_methylation_betas,frozen,True
4,phase2.203.final_probe_mapping,frozen,True
5,phase2.204.confounder_covariates,frozen,True
6,phase2.205.rna_program_discovery_expression,frozen,True
7,phase2.205.methylation_candidate_probe_loadings,frozen,True
8,phase4.401.consensus_transcriptomic_program_ca...,frozen,True
9,phase4.401.consensus_tumor_arm_context,frozen,True


In [4]:
# =============================================================================
# Load frozen tabular upstream inputs
# =============================================================================

sample_mapping = pd.read_csv(
    upstream_artifact_paths["phase2.203.final_sample_mapping"]
)

probe_mapping = pd.read_csv(
    upstream_artifact_paths["phase2.203.final_probe_mapping"],
    low_memory=False
)

confounder_covariates = pd.read_csv(
    upstream_artifact_paths["phase2.204.confounder_covariates"]
)

methylation_probe_loadings = pd.read_csv(
    upstream_artifact_paths[
        "phase2.205.methylation_candidate_probe_loadings"
    ]
)

consensus_program_catalog = pd.read_csv(
    upstream_artifact_paths[
        "phase4.401.consensus_transcriptomic_program_catalog"
    ]
)

consensus_tumor_arm_context = pd.read_csv(
    upstream_artifact_paths[
        "phase4.401.consensus_tumor_arm_context"
    ]
)

print("Sample mapping:", sample_mapping.shape)
print("Probe mapping:", probe_mapping.shape)
print("Confounder covariates:", confounder_covariates.shape)
print("Methylation probe loadings:", methylation_probe_loadings.shape)
print("Consensus program catalog:", consensus_program_catalog.shape)
print("Consensus tumor-arm context:", consensus_tumor_arm_context.shape)

Sample mapping: (9965, 30)
Probe mapping: (455355, 14)
Confounder covariates: (9965, 18)
Methylation probe loadings: (10000, 29)
Consensus program catalog: (3, 21)
Consensus tumor-arm context: (4, 25)


In [5]:
# =============================================================================
# Inspect fields required for notebook-451 transformations
# =============================================================================

print(
    "Methylation probe loadings columns:",
    methylation_probe_loadings.columns.tolist(),
)
print()
print(
    "Consensus tumor-arm context columns:",
    consensus_tumor_arm_context.columns.tolist(),
)
print()
print(
    "Sample mapping columns:",
    sample_mapping.columns.tolist(),
)
print()
print(
    "Confounder covariates columns:",
    confounder_covariates.columns.tolist(),
)

Methylation probe loadings columns: ['model_matrix_row_index', 'representation', 'methylation_platform', 'matrix_row_index', 'probe_id', 'source_platform_probe_order', 'source_shared_probe_order', 'probe_missing_beta_fraction', 'probe_qc_eligibility_scope', 'probe_qc_eligible', 'hm27_missing_beta_fraction', 'hm450_missing_beta_fraction', 'hm27_probe_qc_eligible', 'hm450_probe_qc_eligible', 'shared_probe_qc_eligible', 'shared_matrix_row_index', 'median_within_project_variance', 'METH_IC152', 'METH_IC232', 'METH_IC169', 'METH_IC128', 'METH_IC023', 'METH_IC013', 'METH_IC234', 'METH_IC050', 'METH_IC107', 'METH_IC241', 'METH_IC109', 'METH_IC033']

Consensus tumor-arm context columns: ['consensus_program_id', 'candidate_pair', 'rna_component', 'methylation_component', 'structural_family', 'cell_line_program', 'orientation_multiplier', 'final_audit_status', 'scientific_priority', 'strict_hm27_status', 'relationship_form', 'primary_limitation', 'consensus_handling', 'lopo_absolute_shift', 'lop

In [6]:
# =============================================================================
# Define frozen notebook-451 methylation-component context
# =============================================================================

methylation_component_context = (
    consensus_tumor_arm_context[
        [
            "consensus_program_id",
            "candidate_pair",
            "rna_component",
            "methylation_component",
            "final_audit_status",
            "scientific_priority",
            "primary_limitation",
            "consensus_handling",
        ]
    ]
    .drop_duplicates()
    .sort_values(
        ["consensus_program_id", "methylation_component", "candidate_pair"]
    )
    .reset_index(drop=True)
)

relevant_methylation_components = tuple(
    sorted(
        methylation_component_context[
            "methylation_component"
        ].dropna().unique()
    )
)

missing_loading_components = sorted(
    set(relevant_methylation_components)
    - set(methylation_probe_loadings.columns)
)

print(
    "Consensus programs represented:",
    methylation_component_context["consensus_program_id"].nunique(),
)
print(
    "Tumor methylation arms represented:",
    methylation_component_context.shape[0],
)
print(
    "Unique methylation components:",
    relevant_methylation_components,
)
print(
    "All relevant components present in frozen loadings:",
    not missing_loading_components,
)

methylation_component_context

Consensus programs represented: 3
Tumor methylation arms represented: 4
Unique methylation components: ('METH_IC050', 'METH_IC128', 'METH_IC169')
All relevant components present in frozen loadings: True


,consensus_program_id,candidate_pair,rna_component,methylation_component,final_audit_status,scientific_priority,primary_limitation,consensus_handling
0,CONSENSUS_TX_01,CROSS_OMIC_PAIR_04,RNA_IC150,METH_IC128,CONFOUNDED,LOW,Effect fell from original 0.133 to HM450 refit...,Platform support does not rehabilitate biologi...
1,CONSENSUS_TX_02,CROSS_OMIC_PAIR_08,RNA_IC151,METH_IC050,METHOD_LIMITED,MEDIUM,No stable strict HM27 component recovery,Carry as a secondary small-effect candidate; d...
2,CONSENSUS_TX_03,CROSS_OMIC_PAIR_12,RNA_IC184,METH_IC128,CONFOUNDED,LOW_CONDITIONAL,No valid HM27 test and interpretation remains ...,Do not promote automatically; require the exis...
3,CONSENSUS_TX_03,CROSS_OMIC_PAIR_03,RNA_IC184,METH_IC169,METHOD_LIMITED,CONDITIONAL_HIGH,HM450-only matching missed the frozen score-co...,Retain as the main continuous hypothesis but d...


In [7]:
# =============================================================================
# Construct strong-loading CpG membership universe
# =============================================================================

LOADING_TAIL_SIZE = 50

strong_loading_memberships = []

for component in relevant_methylation_components:
    component_loadings = methylation_probe_loadings[
        ["model_matrix_row_index", "probe_id", component]
    ].rename(columns={component: "loading"})

    negative_tail = (
        component_loadings
        .sort_values(
            ["loading", "probe_id"],
            ascending=[True, True],
        )
        .head(LOADING_TAIL_SIZE)
        .assign(
            methylation_component=component,
            loading_tail="negative",
        )
    )

    positive_tail = (
        component_loadings
        .sort_values(
            ["loading", "probe_id"],
            ascending=[False, True],
        )
        .head(LOADING_TAIL_SIZE)
        .assign(
            methylation_component=component,
            loading_tail="positive",
        )
    )

    strong_loading_memberships.extend(
        [negative_tail, positive_tail]
    )

strong_loading_cpg_memberships = (
    pd.concat(
        strong_loading_memberships,
        ignore_index=True,
    )
    [
        [
            "probe_id",
            "model_matrix_row_index",
            "methylation_component",
            "loading",
            "loading_tail",
        ]
    ]
    .sort_values(
        ["methylation_component", "loading_tail", "loading"],
        ascending=[True, True, True],
    )
    .reset_index(drop=True)
)

expected_memberships = (
    len(relevant_methylation_components)
    * 2
    * LOADING_TAIL_SIZE
)

print("Expected component-tail memberships:", expected_memberships)
print(
    "Observed component-tail memberships:",
    strong_loading_cpg_memberships.shape[0],
)
print(
    "Unique strong-loading CpGs:",
    strong_loading_cpg_memberships["probe_id"].nunique(),
)
print(
    "Duplicate membership rows:",
    strong_loading_cpg_memberships.duplicated(
        ["probe_id", "methylation_component", "loading_tail"]
    ).sum(),
)

strong_loading_cpg_memberships.groupby(
    ["methylation_component", "loading_tail"]
).size()

Expected component-tail memberships: 300
Observed component-tail memberships: 300
Unique strong-loading CpGs: 279
Duplicate membership rows: 0


methylation_component  loading_tail
METH_IC050             negative        50
                       positive        50
METH_IC128             negative        50
                       positive        50
METH_IC169             negative        50
                       positive        50
dtype: int64

In [8]:
# =============================================================================
# Construct unique strong-loading CpG locus universe
# =============================================================================

probe_index_counts = (
    strong_loading_cpg_memberships
    .groupby("probe_id")["model_matrix_row_index"]
    .nunique()
)

if not probe_index_counts.eq(1).all():
    raise ValueError(
        "At least one strong-loading CpG maps to multiple model matrix rows."
    )

strong_loading_cpg_universe = (
    strong_loading_cpg_memberships
    .groupby(
        ["probe_id", "model_matrix_row_index"],
        as_index=False,
    )
    .agg(
        n_methylation_components=(
            "methylation_component",
            "nunique",
        ),
        methylation_components=(
            "methylation_component",
            lambda values: "|".join(sorted(set(values))),
        ),
        component_tail_memberships=(
            "methylation_component",
            lambda values: "|".join(
                sorted(set(values))
            ),
        ),
    )
)

component_tail_context = (
    strong_loading_cpg_memberships
    .assign(
        component_tail=lambda frame: (
            frame["methylation_component"]
            + ":"
            + frame["loading_tail"]
        )
    )
    .groupby("probe_id")["component_tail"]
    .agg(lambda values: "|".join(sorted(set(values))))
)

strong_loading_cpg_universe[
    "component_tail_memberships"
] = strong_loading_cpg_universe["probe_id"].map(
    component_tail_context
)

strong_loading_cpg_universe = (
    strong_loading_cpg_universe
    .sort_values("probe_id")
    .reset_index(drop=True)
)

print(
    "Unique strong-loading CpGs:",
    strong_loading_cpg_universe.shape[0],
)
print(
    "CpGs represented in >1 methylation component:",
    int(
        strong_loading_cpg_universe[
            "n_methylation_components"
        ].gt(1).sum()
    ),
)
print(
    "Maximum component memberships for one CpG:",
    int(
        strong_loading_cpg_universe[
            "n_methylation_components"
        ].max()
    ),
)

strong_loading_cpg_universe[
    "n_methylation_components"
].value_counts().sort_index()

Unique strong-loading CpGs: 279
CpGs represented in >1 methylation component: 21
Maximum component memberships for one CpG: 2


n_methylation_components
1    258
2     21
Name: count, dtype: int64

In [9]:
# =============================================================================
# Map strong-loading CpGs to frozen HM450 matrix rows
# =============================================================================

hm450_probe_mapping = (
    probe_mapping.loc[
        probe_mapping["representation"].eq("hm450"),
        [
            "probe_id",
            "matrix_row_index",
            "probe_missing_beta_fraction",
            "probe_qc_eligible",
            "hm450_missing_beta_fraction",
            "hm450_probe_qc_eligible",
        ],
    ]
    .rename(
        columns={
            "matrix_row_index": "hm450_matrix_row_index",
        }
    )
)

hm450_strong_probe_mapping = (
    strong_loading_cpg_universe
    .merge(
        hm450_probe_mapping,
        on="probe_id",
        how="left",
        validate="one_to_one",
    )
    .sort_values("probe_id")
    .reset_index(drop=True)
)

if hm450_strong_probe_mapping["hm450_matrix_row_index"].isna().any():
    raise ValueError(
        "At least one strong-loading CpG lacks an HM450 matrix-row mapping."
    )

print(
    "Strong-loading CpGs:",
    hm450_strong_probe_mapping.shape[0],
)
print(
    "Mapped to HM450 rows:",
    hm450_strong_probe_mapping[
        "hm450_matrix_row_index"
    ].notna().sum(),
)
print(
    "HM450 QC-eligible:",
    hm450_strong_probe_mapping[
        "hm450_probe_qc_eligible"
    ].fillna(False).sum(),
)
print(
    "Unique HM450 matrix rows:",
    hm450_strong_probe_mapping[
        "hm450_matrix_row_index"
    ].nunique(),
)

Strong-loading CpGs: 279
Mapped to HM450 rows: 279
HM450 QC-eligible: 279
Unique HM450 matrix rows: 279


In [10]:
# =============================================================================
# Inspect frozen RNA expression HDF5 structure
# =============================================================================

rna_expression_path = upstream_artifact_paths[
    "phase2.205.rna_program_discovery_expression"
]

with h5py.File(rna_expression_path, "r") as h5_file:
    print("Root keys:", list(h5_file.keys()))
    print("File attributes:", dict(h5_file.attrs))

    rna_logcpm_dataset = h5_file["logcpm"]

    print("logcpm shape:", rna_logcpm_dataset.shape)
    print("logcpm dtype:", rna_logcpm_dataset.dtype)
    print(
        "logcpm attributes:",
        dict(rna_logcpm_dataset.attrs),
    )

Root keys: ['logcpm']
File attributes: {}
logcpm shape: (18123, 9965)
logcpm dtype: float64
logcpm attributes: {'orientation': array([b'genes_x_samples'], dtype='|S16'), 'rhdf5-NA.OK': array([1], dtype=int32)}


In [11]:
# =============================================================================
# Load RNA program-discovery gene metadata
# =============================================================================

RNA_DISCOVERY_GENE_METADATA_PATH = (
    Paths.expression
    / "tcga_primary_tumor_rnaseq_program_discovery_filtered_gene_metadata.csv"
)

if not RNA_DISCOVERY_GENE_METADATA_PATH.is_file():
    raise FileNotFoundError(
        "Frozen RNA program-discovery gene metadata is missing."
    )

rna_discovery_gene_metadata = pd.read_csv(
    RNA_DISCOVERY_GENE_METADATA_PATH
)

with h5py.File(rna_expression_path, "r") as h5_file:
    rna_logcpm_shape = h5_file["logcpm"].shape

if len(rna_discovery_gene_metadata) != rna_logcpm_shape[0]:
    raise ValueError(
        "RNA gene metadata rows do not match the frozen logCPM gene axis."
    )

if len(sample_mapping) != rna_logcpm_shape[1]:
    raise ValueError(
        "Frozen sample mapping rows do not match the logCPM sample axis."
    )

print(
    "RNA gene metadata path:",
    project_relative_path(RNA_DISCOVERY_GENE_METADATA_PATH),
)
print("RNA gene metadata shape:", rna_discovery_gene_metadata.shape)
print("RNA gene metadata columns:", rna_discovery_gene_metadata.columns.tolist())
print(
    "Gene-axis alignment:",
    len(rna_discovery_gene_metadata) == rna_logcpm_shape[0],
)
print(
    "Sample-axis alignment:",
    len(sample_mapping) == rna_logcpm_shape[1],
)

RNA gene metadata path: data/interim/expression/tcga_primary_tumor_rnaseq_program_discovery_filtered_gene_metadata.csv
RNA gene metadata shape: (18123, 7)
RNA gene metadata columns: ['matrix_row_index', 'gene_id', 'gene_name', 'gene_type', 'gene_id_base', 'gene_id_is_versioned', 'expressed_sample_count']
Gene-axis alignment: True
Sample-axis alignment: True


In [12]:
# =============================================================================
# Construct frozen RNA expression gene index
# =============================================================================

rna_expression_gene_index = (
    rna_discovery_gene_metadata
    .assign(
        rna_logcpm_row_index=np.arange(
            len(rna_discovery_gene_metadata),
            dtype=np.int64,
        )
    )
    [
        [
            "rna_logcpm_row_index",
            "matrix_row_index",
            "gene_id",
            "gene_id_base",
            "gene_name",
            "gene_type",
            "gene_id_is_versioned",
            "expressed_sample_count",
        ]
    ]
    .copy()
)

if rna_expression_gene_index["rna_logcpm_row_index"].duplicated().any():
    raise ValueError("RNA logCPM row indices are not unique.")

if rna_expression_gene_index["matrix_row_index"].duplicated().any():
    raise ValueError("Frozen upstream RNA matrix row indices are not unique.")

gene_name_counts = (
    rna_expression_gene_index["gene_name"]
    .dropna()
    .value_counts()
)

gene_id_base_counts = (
    rna_expression_gene_index["gene_id_base"]
    .dropna()
    .value_counts()
)

print("RNA expression genes:", len(rna_expression_gene_index))
print(
    "Unique Ensembl base IDs:",
    rna_expression_gene_index["gene_id_base"].nunique(),
)
print(
    "Ensembl base IDs represented by >1 row:",
    int(gene_id_base_counts.gt(1).sum()),
)
print(
    "Unique gene symbols:",
    rna_expression_gene_index["gene_name"].nunique(),
)
print(
    "Gene symbols represented by >1 row:",
    int(gene_name_counts.gt(1).sum()),
)
print(
    "Missing gene symbols:",
    int(rna_expression_gene_index["gene_name"].isna().sum()),
)

RNA expression genes: 18123
Unique Ensembl base IDs: 18123
Ensembl base IDs represented by >1 row: 0
Unique gene symbols: 18122
Gene symbols represented by >1 row: 1
Missing gene symbols: 0


In [13]:
# =============================================================================
# Characterize RNA gene-symbol ambiguity
# =============================================================================

duplicated_gene_symbols = (
    gene_name_counts.loc[gene_name_counts.gt(1)]
    .index
    .tolist()
)

ambiguous_gene_symbol_rows = (
    rna_expression_gene_index.loc[
        rna_expression_gene_index["gene_name"].isin(
            duplicated_gene_symbols
        )
    ]
    .sort_values(
        ["gene_name", "gene_id_base"]
    )
    .reset_index(drop=True)
)

print(
    "Ambiguous gene symbols:",
    len(duplicated_gene_symbols),
)
print(
    "RNA rows involved:",
    len(ambiguous_gene_symbol_rows),
)

ambiguous_gene_symbol_rows[
    [
        "rna_logcpm_row_index",
        "gene_id",
        "gene_id_base",
        "gene_name",
        "gene_type",
    ]
]

Ambiguous gene symbols: 1
RNA rows involved: 2


,rna_logcpm_row_index,gene_id,gene_id_base,gene_name,gene_type
0,11882,ENSG00000168255.20,ENSG00000168255,POLR2J3,protein_coding
1,18094,ENSG00000285437.1,ENSG00000285437,POLR2J3,protein_coding


In [14]:
# =============================================================================
# Define deterministic RNA gene-identifier lookup tables
# =============================================================================

rna_ensembl_lookup = (
    rna_expression_gene_index[
        [
            "gene_id_base",
            "gene_name",
            "rna_logcpm_row_index",
            "matrix_row_index",
        ]
    ]
    .set_index("gene_id_base")
)

if not rna_ensembl_lookup.index.is_unique:
    raise ValueError(
        "RNA Ensembl base-ID lookup contains duplicated index values."
    )

unambiguous_gene_symbols = gene_name_counts.loc[
    gene_name_counts.eq(1)
].index

rna_symbol_lookup = (
    rna_expression_gene_index.loc[
        rna_expression_gene_index["gene_name"].isin(
            unambiguous_gene_symbols
        ),
        [
            "gene_name",
            "gene_id_base",
            "rna_logcpm_row_index",
            "matrix_row_index",
        ],
    ]
    .set_index("gene_name")
)

if not rna_symbol_lookup.index.is_unique:
    raise ValueError(
        "RNA gene-symbol lookup contains duplicated index values."
    )

print(
    "Ensembl lookup entries:",
    len(rna_ensembl_lookup),
)
print(
    "Unambiguous gene-symbol lookup entries:",
    len(rna_symbol_lookup),
)
print(
    "Excluded ambiguous gene symbols:",
    len(duplicated_gene_symbols),
)
print(
    "Ambiguous symbols:",
    duplicated_gene_symbols,
)

Ensembl lookup entries: 18123
Unambiguous gene-symbol lookup entries: 18121
Excluded ambiguous gene symbols: 1
Ambiguous symbols: ['POLR2J3']


### **CpG biological-annotation checkpoint**

The strong-loading CpG universe and the frozen RNA expression gene axis have now
been defined independently of methylation–expression association results.

Before constructing CpG–gene pairs, notebook 451 requires one authoritative,
versioned biological annotation resource for HM450 probes.

The annotation resource must provide, where available:

- CpG probe identity;
- genomic coordinates;
- genome build;
- gene association;
- promoter or other regulatory-context annotation; and
- sufficient provenance to reproduce the mapping deterministically.

The annotation authority must be frozen before any methylation–expression
association is calculated.

Primary CpG-to-gene assignment will follow the prespecified identifier policy:

1. exact Ensembl base-ID matching when the annotation resource provides a
   compatible stable Ensembl gene identifier;
2. otherwise exact gene-symbol matching only when the symbol is unambiguous in
   the frozen RNA expression matrix.

No fuzzy matching, nearest-gene rescue, manual alias substitution, or
result-driven reassignment is permitted in the primary analysis.

The frozen RNA expression representation contains 18,123 genes with unique
Ensembl base identifiers. Gene-symbol mapping is unambiguous for 18,121 genes.
`POLR2J3` is represented by two distinct Ensembl genes and therefore cannot be
assigned through symbol-only matching.

CpGs mapping to multiple defensible genes will retain every valid CpG–gene
relationship as separate candidate pairs. Repeated transcript-level annotations
of the same CpG–gene relationship will later be collapsed to one unique
inferential CpG–gene unit while preserving annotation metadata.

No methylation–expression inference proceeds until the annotation resource,
version, genome build, provenance, and local frozen representation have been
defined and audited.

### **Frozen CpG annotation authority**

Notebook 451 uses a single prespecified biological annotation authority for
HM450 CpG probes:

- annotation framework: `SeSAMe / sesameData`;
- methylation platform: `HM450`;
- genome build: `hg38`.

This decision is frozen before inspection of any locus-level
methylation–expression association.

The annotation resource will be used only to establish deterministic biological
context for the frozen strong-loading CpG universe, including, where available:

- genomic coordinates;
- CpG-to-gene relationships; and
- promoter or other regulatory-context annotation.

The selected annotation authority does not replace or modify the frozen
technical probe mapping produced in Phase 2. The Phase 2 probe mapping remains
authoritative for matrix-row identity, QC eligibility, platform membership, and
missingness.

Notebook 451 will therefore preserve two distinct annotation layers:

1. **technical probe identity and matrix mapping** inherited from Phase 2; and
2. **biological CpG annotation** derived from the frozen SeSAMe HM450 hg38
   resource.

No alternative annotation source may be substituted after association results
are inspected because it yields more favorable CpG-to-gene mappings or
regulatory interpretation.

The exact SeSAMe / sesameData version, resource identity, retrieval procedure,
local path, and cryptographic identity must be recorded before inferential
analysis begins.

In [15]:
# =============================================================================
# Define frozen CpG annotation resource specification
# =============================================================================

CPG_ANNOTATION_SPEC = {
    "source_database": "Bioconductor",
    "provider": "SeSAMe / sesameData",
    "bioconductor_release": "3.23",
    "package": "sesameData",
    "package_version": "1.30.0",
    "platform": "HM450",
    "genome_build": "hg38",
    "resource_role": "cpg_gene_regulatory_annotation",
}

print("CpG annotation authority:")
for key, value in CPG_ANNOTATION_SPEC.items():
    print(f"  {key}: {value}")

CpG annotation authority:
  source_database: Bioconductor
  provider: SeSAMe / sesameData
  bioconductor_release: 3.23
  package: sesameData
  package_version: 1.30.0
  platform: HM450
  genome_build: hg38
  resource_role: cpg_gene_regulatory_annotation


In [16]:
# =============================================================================
# Inspect raw-data registry for CpG annotation authority
# =============================================================================

with Paths.raw_data_registry.open("r", encoding="utf-8") as handle:
    raw_data_registry = json.load(handle)

registry_text = json.dumps(
    raw_data_registry,
    sort_keys=True,
).lower()

annotation_registry_terms = (
    "sesamedata",
    "sesame / sesamedata",
)

existing_annotation_registration = any(
    term in registry_text
    for term in annotation_registry_terms
)

print(
    "Existing SeSAMe / sesameData registry entry:",
    existing_annotation_registration,
)

Existing SeSAMe / sesameData registry entry: True


In [17]:
# =============================================================================
# Define planned sesameData HM450 annotation registry entry
# =============================================================================

SESAME_ANNOTATION_DIR = (
    Paths.tcga
    / "annotations"
    / "sesame_hm450_hg38"
)

SESAME_ANNOTATION_FILENAME = (
    "sesame_hm450_hg38_probe_annotation.csv"
)

SESAME_ANNOTATION_PATH = (
    SESAME_ANNOTATION_DIR
    / SESAME_ANNOTATION_FILENAME
)

sesame_annotation_registry_entry = {
    "provenance_mode": "file_managed",
    "source_database": "Bioconductor",
    "provider": "SeSAMe / sesameData",
    "release": CPG_ANNOTATION_SPEC["bioconductor_release"],
    "package": CPG_ANNOTATION_SPEC["package"],
    "package_version": CPG_ANNOTATION_SPEC["package_version"],
    "platform": CPG_ANNOTATION_SPEC["platform"],
    "genome_build": CPG_ANNOTATION_SPEC["genome_build"],
    "status": "planned",
    "canonical_dir": project_relative_path(
        SESAME_ANNOTATION_DIR
    ),
    "files": {
        SESAME_ANNOTATION_FILENAME: {
            "role": "cpg_gene_regulatory_annotation",
            "status": "planned",
        }
    },
}

print(
    "Planned annotation path:",
    project_relative_path(SESAME_ANNOTATION_PATH),
)
print()
print(
    json.dumps(
        sesame_annotation_registry_entry,
        indent=2,
    )
)

Planned annotation path: data/raw/tcga/annotations/sesame_hm450_hg38/sesame_hm450_hg38_probe_annotation.csv

{
  "provenance_mode": "file_managed",
  "source_database": "Bioconductor",
  "provider": "SeSAMe / sesameData",
  "release": "3.23",
  "package": "sesameData",
  "package_version": "1.30.0",
  "platform": "HM450",
  "genome_build": "hg38",
  "status": "planned",
  "canonical_dir": "data/raw/tcga/annotations/sesame_hm450_hg38",
  "files": {
    "sesame_hm450_hg38_probe_annotation.csv": {
      "role": "cpg_gene_regulatory_annotation",
      "status": "planned"
    }
  }
}


In [18]:
# =============================================================================
# Resolve and fingerprint frozen CpG annotation artifacts
# =============================================================================

cpg_annotation_dir = (
    Paths.tcga
    / "annotations"
    / "sesame_hm450_hg38"
)

cpg_coverage_path = (
    cpg_annotation_dir
    / "sesame_hm450_hg38_cpg_annotation_coverage.csv"
)

cpg_gene_annotation_path = (
    cpg_annotation_dir
    / "sesame_hm450_hg38_cpg_gene_regulatory_annotation.csv"
)

cpg_annotation_metadata_path = (
    cpg_annotation_dir
    / "sesame_hm450_hg38_annotation_metadata.csv"
)

annotation_paths = {
    "cpg_annotation_coverage": cpg_coverage_path,
    "cpg_gene_regulatory_annotation": cpg_gene_annotation_path,
    "annotation_metadata": cpg_annotation_metadata_path,
}

annotation_fingerprints = pd.DataFrame(
    [
        {
            "artifact": name,
            "path": project_relative_path(path),
            "size_bytes": path.stat().st_size,
            "sha256": calculate_sha256(path),
        }
        for name, path in annotation_paths.items()
    ]
)

print(annotation_fingerprints.to_string(index=False))

                      artifact                                                                                             path  size_bytes                                                           sha256
       cpg_annotation_coverage        data/raw/tcga/annotations/sesame_hm450_hg38/sesame_hm450_hg38_cpg_annotation_coverage.csv    38862313 abcb074a7a24d67482208979bd1a722540b15180e77c62b1dab1b46de51a41e8
cpg_gene_regulatory_annotation data/raw/tcga/annotations/sesame_hm450_hg38/sesame_hm450_hg38_cpg_gene_regulatory_annotation.csv    96590760 9f503c381dd5c74b5d6cac7f327383d278de5f124a7ecc5240536e189f9c95b1
           annotation_metadata            data/raw/tcga/annotations/sesame_hm450_hg38/sesame_hm450_hg38_annotation_metadata.csv        1593 e66f34da5456541fe18ccd3174284b2a56139b8c70cbf3764f4a201136f08fbf


In [19]:
# =============================================================================
# Load and validate frozen CpG annotation artifacts
# =============================================================================

cpg_annotation_coverage = pd.read_csv(
    cpg_coverage_path,
    low_memory=False,
)

cpg_gene_annotation = pd.read_csv(
    cpg_gene_annotation_path,
    low_memory=False,
)

cpg_annotation_metadata = pd.read_csv(
    cpg_annotation_metadata_path,
)

expected_coverage_columns = {
    "probe_id",
    "cpg_chr",
    "cpg_start",
    "cpg_end",
    "n_protein_coding_genes",
    "n_promoter_genes",
    "n_transcript_genes",
    "promoter_associated",
    "transcript_associated",
    "annotation_status",
}

expected_pair_columns = {
    "probe_id",
    "gene_id_base",
    "promoter_transcript_count",
    "genic_transcript_count",
    "promoter_associated",
    "transcript_associated",
    "cpg_chr",
    "cpg_start",
    "cpg_end",
    "gene_id",
    "gene_name",
    "promoter_transcript_ids",
    "genic_transcript_ids",
}

if set(cpg_annotation_coverage.columns) != expected_coverage_columns:
    raise ValueError(
        "Unexpected CpG annotation coverage schema."
    )

if set(cpg_gene_annotation.columns) != expected_pair_columns:
    raise ValueError(
        "Unexpected CpG-gene annotation schema."
    )

if list(cpg_annotation_metadata.columns) != ["field", "value"]:
    raise ValueError(
        "Unexpected annotation metadata schema."
    )

if cpg_annotation_coverage.shape[0] != 482_389:
    raise ValueError(
        "Unexpected number of CpG annotation coverage rows."
    )

if cpg_gene_annotation.shape[0] != 441_122:
    raise ValueError(
        "Unexpected number of CpG-gene annotation rows."
    )

if cpg_annotation_metadata.shape[0] != 37:
    raise ValueError(
        "Unexpected number of annotation metadata rows."
    )

if not cpg_annotation_coverage["probe_id"].is_unique:
    raise ValueError(
        "CpG annotation coverage contains duplicated probe IDs."
    )

pair_index = pd.MultiIndex.from_frame(
    cpg_gene_annotation[
        ["probe_id", "gene_id_base"]
    ]
)

if not pair_index.is_unique:
    raise ValueError(
        "CpG-gene annotation contains duplicated inferential pairs."
    )

if cpg_annotation_metadata["field"].duplicated().any():
    raise ValueError(
        "Annotation metadata contains duplicated fields."
    )

metadata_lookup = (
    cpg_annotation_metadata
    .set_index("field")["value"]
    .astype(str)
)

expected_metadata = {
    "source_database": "Bioconductor",
    "provider": "SeSAMe / sesameData",
    "bioconductor_release": "3.23",
    "sesameData_version": "1.30.0",
    "platform": "HM450",
    "genome_build": "hg38",
    "manifest_resource": "HM450.address",
    "manifest_resource_ehid": "EH7317",
    "manifest_resource_version": "1.13.1",
    "genome_resource": "genomeInfo.hg38",
    "genome_resource_ehid": "EH8558",
    "genome_resource_version": "1.21.1",
    "promoter_upstream_bp": "1500",
    "promoter_downstream_bp": "1500",
    "hm450_cpg_probes": "482389",
    "protein_coding_genes": "19962",
    "unique_cpg_gene_pairs": "441122",
}

for field, expected_value in expected_metadata.items():
    observed_value = metadata_lookup.get(field)

    if observed_value != expected_value:
        raise ValueError(
            f"Unexpected annotation metadata for {field}: "
            f"{observed_value!r}"
        )

allowed_annotation_status = {
    "promoter_and_transcript",
    "promoter_only",
    "transcript_only",
    "no_protein_coding_gene_mapping",
}

observed_annotation_status = set(
    cpg_annotation_coverage["annotation_status"].unique()
)

if observed_annotation_status != allowed_annotation_status:
    raise ValueError(
        "Unexpected CpG annotation-status categories."
    )

print(
    "CpG annotation coverage:",
    cpg_annotation_coverage.shape,
)

print(
    "CpG-gene regulatory annotation:",
    cpg_gene_annotation.shape,
)

print(
    "Annotation metadata:",
    cpg_annotation_metadata.shape,
)

print(
    "Unique CpG IDs:",
    cpg_annotation_coverage["probe_id"].nunique(),
)

print(
    "Unique CpG-gene pairs:",
    len(pair_index),
)

print(
    "\nCpG annotation status:"
)

print(
    cpg_annotation_coverage[
        "annotation_status"
    ].value_counts()
)

CpG annotation coverage: (482389, 10)
CpG-gene regulatory annotation: (441122, 13)
Annotation metadata: (37, 2)
Unique CpG IDs: 482389
Unique CpG-gene pairs: 441122

CpG annotation status:
annotation_status
promoter_and_transcript           171224
transcript_only                   133427
no_protein_coding_gene_mapping    108078
promoter_only                      69660
Name: count, dtype: int64


In [20]:
# =============================================================================
# Prepare frozen SeSAMe HM450 hg38 raw-data registry entry
# =============================================================================

fingerprint_lookup = (
    annotation_fingerprints
    .set_index("artifact")
    .to_dict(orient="index")
)

sesame_annotation_registry_entry = {
    "provenance_mode": "file_managed",
    "source_database": "Bioconductor",
    "provider": "SeSAMe / sesameData",
    "release": "Bioconductor 3.23",
    "package": "sesameData",
    "package_version": "1.30.0",
    "platform": "HM450",
    "genome_build": "hg38",
    "status": "acquired_and_used",
    "retrieval_date": "2026-09-08",
    "canonical_dir": (
        "data/raw/tcga/annotations/sesame_hm450_hg38"
    ),
    "resources": {
        "HM450.address": {
            "ehid": "EH7317",
            "version": "1.13.1",
            "source_version": "2022-01-23",
        },
        "genomeInfo.hg38": {
            "ehid": "EH8558",
            "version": "1.21.1",
            "source_version": "2024-01-11",
        },
    },
    "derivation": {
        "script": (
            "scripts/phase4b/"
            "export_sesamedata_hm450_hg38_annotation.R"
        ),
        "promoter_method": "GenomicRanges::promoters",
        "promoter_upstream_bp": 1500,
        "promoter_downstream_bp": 1500,
        "overlap_strand_policy": "ignore.strand=TRUE",
        "gene_annotation_scope": "protein_coding",
        "cpg_identifier_rule": "^cg[0-9]{8}$",
    },
    "files": {
        cpg_coverage_path.name: {
            "role": "cpg_annotation_coverage",
            "status": "acquired_and_used",
            "size_bytes": fingerprint_lookup[
                "cpg_annotation_coverage"
            ]["size_bytes"],
            "sha256": fingerprint_lookup[
                "cpg_annotation_coverage"
            ]["sha256"],
        },
        cpg_gene_annotation_path.name: {
            "role": "cpg_gene_regulatory_annotation",
            "status": "acquired_and_used",
            "size_bytes": fingerprint_lookup[
                "cpg_gene_regulatory_annotation"
            ]["size_bytes"],
            "sha256": fingerprint_lookup[
                "cpg_gene_regulatory_annotation"
            ]["sha256"],
        },
        cpg_annotation_metadata_path.name: {
            "role": "annotation_derivation_metadata",
            "status": "acquired_and_used",
            "size_bytes": fingerprint_lookup[
                "annotation_metadata"
            ]["size_bytes"],
            "sha256": fingerprint_lookup[
                "annotation_metadata"
            ]["sha256"],
        },
    },
}

print(
    json.dumps(
        sesame_annotation_registry_entry,
        indent=2,
    )
)

{
  "provenance_mode": "file_managed",
  "source_database": "Bioconductor",
  "provider": "SeSAMe / sesameData",
  "release": "Bioconductor 3.23",
  "package": "sesameData",
  "package_version": "1.30.0",
  "platform": "HM450",
  "genome_build": "hg38",
  "status": "acquired_and_used",
  "retrieval_date": "2026-09-08",
  "canonical_dir": "data/raw/tcga/annotations/sesame_hm450_hg38",
  "resources": {
    "HM450.address": {
      "ehid": "EH7317",
      "version": "1.13.1",
      "source_version": "2022-01-23"
    },
    "genomeInfo.hg38": {
      "ehid": "EH8558",
      "version": "1.21.1",
      "source_version": "2024-01-11"
    }
  },
  "derivation": {
    "script": "scripts/phase4b/export_sesamedata_hm450_hg38_annotation.R",
    "promoter_method": "GenomicRanges::promoters",
    "promoter_upstream_bp": 1500,
    "promoter_downstream_bp": 1500,
    "overlap_strand_policy": "ignore.strand=TRUE",
    "gene_annotation_scope": "protein_coding",
    "cpg_identifier_rule": "^cg[0-9]{8}$"


In [21]:
# =============================================================================
# Freeze SeSAMe HM450 hg38 annotation in raw-data registry
# =============================================================================

registry_key = "sesame_hm450_hg38_annotation"

observed_entry = register_json_entry(
    Paths.raw_data_registry,
    (
        "tcga",
        "external_resources",
        registry_key,
    ),
    sesame_annotation_registry_entry,
)

print("Registered:", registry_key)
print(
    "Registry:",
    project_relative_path(Paths.raw_data_registry),
)
print("Status:", observed_entry["status"])
print("Files registered:", len(observed_entry["files"]))

Registered: sesame_hm450_hg38_annotation
Registry: config/raw_data_registry.json
Status: acquired_and_used
Files registered: 3


In [22]:
# =============================================================================
# Verify frozen SeSAMe registry entry against current local files
# =============================================================================

raw_data_registry = load_json_registry(
    Paths.raw_data_registry
)

registered_entry = (
    raw_data_registry["tcga"]["external_resources"][
        "sesame_hm450_hg38_annotation"
    ]
)

registered_files = registered_entry["files"]

for artifact_name, artifact_path in annotation_paths.items():
    file_name = artifact_path.name
    file_record = registered_files[file_name]

    observed_size = artifact_path.stat().st_size
    observed_sha256 = calculate_sha256(artifact_path)

    if observed_size != file_record["size_bytes"]:
        raise ValueError(
            f"Size mismatch for {file_name}: "
            f"{observed_size} != {file_record['size_bytes']}"
        )

    if observed_sha256 != file_record["sha256"]:
        raise ValueError(
            f"SHA256 mismatch for {file_name}"
        )

print(
    "Registry freeze verified:",
    "sesame_hm450_hg38_annotation",
)

print(
    "Files verified:",
    len(registered_files),
)

print(
    "Status:",
    registered_entry["status"],
)

Registry freeze verified: sesame_hm450_hg38_annotation
Files verified: 3
Status: acquired_and_used


In [23]:
# =============================================================================
# Map strong-loading CpGs to frozen biological annotation
# =============================================================================

strong_cpg_annotation_coverage = (
    strong_loading_cpg_universe
    .merge(
        cpg_annotation_coverage,
        on="probe_id",
        how="left",
        validate="one_to_one",
    )
    .sort_values("probe_id")
    .reset_index(drop=True)
)

if len(strong_cpg_annotation_coverage) != len(strong_loading_cpg_universe):
    raise ValueError(
        "Strong-loading CpG universe changed during annotation mapping."
    )

if strong_cpg_annotation_coverage["annotation_status"].isna().any():
    raise ValueError(
        "At least one strong-loading CpG is absent from the frozen "
        "SeSAMe annotation coverage table."
    )

strong_cpg_gene_annotation = (
    cpg_gene_annotation.loc[
        cpg_gene_annotation["probe_id"].isin(
            strong_loading_cpg_universe["probe_id"]
        )
    ]
    .merge(
        strong_loading_cpg_universe,
        on="probe_id",
        how="inner",
        validate="many_to_one",
    )
    .sort_values(
        ["probe_id", "gene_id_base"]
    )
    .reset_index(drop=True)
)

strong_pair_index = pd.MultiIndex.from_frame(
    strong_cpg_gene_annotation[
        ["probe_id", "gene_id_base"]
    ]
)

if not strong_pair_index.is_unique:
    raise ValueError(
        "Strong-loading CpG-gene annotation contains duplicated pairs."
    )

print(
    "Strong-loading CpGs:",
    len(strong_loading_cpg_universe),
)

print(
    "CpGs found in frozen annotation:",
    strong_cpg_annotation_coverage[
        "annotation_status"
    ].notna().sum(),
)

print(
    "CpGs with >=1 protein-coding gene mapping:",
    strong_cpg_annotation_coverage[
        "n_protein_coding_genes"
    ].gt(0).sum(),
)

print(
    "CpGs without protein-coding gene mapping:",
    strong_cpg_annotation_coverage[
        "n_protein_coding_genes"
    ].eq(0).sum(),
)

print(
    "Unique strong-loading CpG-gene pairs:",
    len(strong_pair_index),
)

print(
    "Unique annotated genes:",
    strong_cpg_gene_annotation[
        "gene_id_base"
    ].nunique(),
)

print("\nStrong-loading CpG annotation status:")

print(
    strong_cpg_annotation_coverage[
        "annotation_status"
    ].value_counts()
)

Strong-loading CpGs: 279
CpGs found in frozen annotation: 279
CpGs with >=1 protein-coding gene mapping: 272
CpGs without protein-coding gene mapping: 7
Unique strong-loading CpG-gene pairs: 336
Unique annotated genes: 287

Strong-loading CpG annotation status:
annotation_status
promoter_and_transcript           199
promoter_only                      60
transcript_only                    13
no_protein_coding_gene_mapping      7
Name: count, dtype: int64


In [24]:
# =============================================================================
# Map annotated genes to frozen RNA genes by exact Ensembl base ID
# =============================================================================

rna_ensembl_map = (
    rna_ensembl_lookup
    .reset_index()
    .rename(
        columns={
            "gene_id_base": "rna_gene_id_base",
            "gene_name": "rna_gene_name",
            "matrix_row_index": "rna_matrix_row_index",
        }
    )
)

cpg_gene_harmonization = (
    strong_cpg_gene_annotation
    .rename(
        columns={
            "gene_id": "annotation_gene_id",
            "gene_id_base": "annotation_gene_id_base",
            "gene_name": "annotation_gene_name",
        }
    )
    .merge(
        rna_ensembl_map,
        left_on="annotation_gene_id_base",
        right_on="rna_gene_id_base",
        how="left",
        validate="many_to_one",
    )
)

cpg_gene_harmonization["gene_mapping_method"] = np.where(
    cpg_gene_harmonization["rna_logcpm_row_index"].notna(),
    "ensembl_base_exact",
    pd.NA,
)

print(
    "CpG-gene pairs:",
    len(cpg_gene_harmonization),
)

print(
    "Exact Ensembl matches:",
    cpg_gene_harmonization["rna_logcpm_row_index"].notna().sum(),
)

print(
    "Remaining unmatched:",
    cpg_gene_harmonization["rna_logcpm_row_index"].isna().sum(),
)

CpG-gene pairs: 336
Exact Ensembl matches: 311
Remaining unmatched: 25


In [25]:
# =============================================================================
# Resolve unmatched genes by exact unambiguous gene symbol
# =============================================================================

unmatched_mask = cpg_gene_harmonization[
    "rna_logcpm_row_index"
].isna()

symbol_matches = (
    cpg_gene_harmonization.loc[
        unmatched_mask,
        "annotation_gene_name",
    ]
    .map(rna_symbol_lookup["rna_logcpm_row_index"])
)

symbol_match_mask = (
    unmatched_mask
    & symbol_matches.notna()
)

cpg_gene_harmonization.loc[
    symbol_match_mask,
    "rna_logcpm_row_index",
] = symbol_matches.loc[symbol_match_mask].to_numpy()

cpg_gene_harmonization.loc[
    symbol_match_mask,
    "rna_matrix_row_index",
] = (
    cpg_gene_harmonization.loc[
        symbol_match_mask,
        "annotation_gene_name",
    ]
    .map(rna_symbol_lookup["matrix_row_index"])
    .to_numpy()
)

cpg_gene_harmonization.loc[
    symbol_match_mask,
    "rna_gene_id_base",
] = (
    cpg_gene_harmonization.loc[
        symbol_match_mask,
        "annotation_gene_name",
    ]
    .map(rna_symbol_lookup["gene_id_base"])
    .to_numpy()
)

cpg_gene_harmonization.loc[
    symbol_match_mask,
    "rna_gene_name",
] = cpg_gene_harmonization.loc[
    symbol_match_mask,
    "annotation_gene_name",
].to_numpy()

cpg_gene_harmonization.loc[
    symbol_match_mask,
    "gene_mapping_method",
] = "gene_symbol_exact_unambiguous"

print(
    "Exact unambiguous-symbol matches:",
    int(symbol_match_mask.sum()),
)

print(
    "Remaining unmatched:",
    int(
        cpg_gene_harmonization[
            "rna_logcpm_row_index"
        ].isna().sum()
    ),
)

Exact unambiguous-symbol matches: 0
Remaining unmatched: 25


In [26]:
# =============================================================================
# Inspect unresolved CpG-gene mappings
# =============================================================================

unresolved_gene_mappings = (
    cpg_gene_harmonization.loc[
        cpg_gene_harmonization["rna_logcpm_row_index"].isna(),
        [
            "probe_id",
            "annotation_gene_id",
            "annotation_gene_id_base",
            "annotation_gene_name",
        ],
    ]
    .drop_duplicates()
    .sort_values(
        [
            "annotation_gene_name",
            "annotation_gene_id_base",
            "probe_id",
        ]
    )
    .reset_index(drop=True)
)

print(
    "Unresolved CpG-gene pairs:",
    len(unresolved_gene_mappings),
)

print(
    "Unique unresolved annotation genes:",
    unresolved_gene_mappings[
        "annotation_gene_id_base"
    ].nunique(),
)

unresolved_gene_mappings

Unresolved CpG-gene pairs: 25
Unique unresolved annotation genes: 17


,probe_id,annotation_gene_id,annotation_gene_id_base,annotation_gene_name
0,cg08668790,ENSG00000269026.2,ENSG00000269026,AC003006.1
1,cg21790626,ENSG00000269026.2,ENSG00000269026,AC003006.1
2,cg07778029,ENSG00000257184.3,ENSG00000257184,AC004080.3
3,cg26521404,ENSG00000257184.3,ENSG00000257184,AC004080.3
4,cg27009703,ENSG00000257184.3,ENSG00000257184,AC004080.3
5,cg07339138,ENSG00000280571.2,ENSG00000280571,AC006059.2
6,cg12382902,ENSG00000285901.2,ENSG00000285901,AC008012.1
7,cg16994506,ENSG00000285901.2,ENSG00000285901,AC008012.1
8,cg23776012,ENSG00000264058.2,ENSG00000264058,AC073508.2
9,cg03283421,ENSG00000286088.1,ENSG00000286088,AC073585.1


In [27]:
# =============================================================================
# Finalize CpG-gene to RNA mapping status
# =============================================================================

matched_mask = cpg_gene_harmonization[
    "rna_logcpm_row_index"
].notna()

cpg_gene_harmonization["gene_mapping_status"] = np.where(
    matched_mask,
    "matched",
    "unresolved_not_in_frozen_rna_axis",
)

print(
    cpg_gene_harmonization[
        "gene_mapping_status"
    ].value_counts()
)

print()

print(
    cpg_gene_harmonization[
        "gene_mapping_method"
    ].value_counts(dropna=False)
)

gene_mapping_status
matched                              311
unresolved_not_in_frozen_rna_axis     25
Name: count, dtype: int64

gene_mapping_method
ensembl_base_exact    311
NaN                    25
Name: count, dtype: int64


In [28]:
# =============================================================================
# Construct RNA-resolved CpG-gene candidate pairs
# =============================================================================

rna_resolved_cpg_gene_pairs = (
    cpg_gene_harmonization.loc[
        cpg_gene_harmonization["gene_mapping_status"].eq("matched")
    ]
    .copy()
    .sort_values(["probe_id", "rna_gene_id_base"])
    .reset_index(drop=True)
)

rna_resolved_cpg_gene_pairs[
    ["rna_logcpm_row_index", "rna_matrix_row_index"]
] = rna_resolved_cpg_gene_pairs[
    ["rna_logcpm_row_index", "rna_matrix_row_index"]
].astype(np.int64)

if rna_resolved_cpg_gene_pairs.duplicated(
    ["probe_id", "rna_gene_id_base"]
).any():
    raise ValueError(
        "RNA harmonization produced duplicated CpG-gene analytical units."
    )

print(
    "RNA-resolved CpG-gene pairs:",
    len(rna_resolved_cpg_gene_pairs),
)
print(
    "Unique CpGs:",
    rna_resolved_cpg_gene_pairs["probe_id"].nunique(),
)
print(
    "Unique RNA genes:",
    rna_resolved_cpg_gene_pairs["rna_gene_id_base"].nunique(),
)

RNA-resolved CpG-gene pairs: 311
Unique CpGs: 270
Unique RNA genes: 270


In [29]:
# =============================================================================
# Construct frozen HM450 sample-axis index
# =============================================================================

hm450_sample_index = (
    sample_mapping.loc[
        sample_mapping["hm450_matrix_column_index"].notna(),
        [
            "final_sample_column_index",
            "case_submitter_id",
            "project_id",
            "hm450_matrix_column_index",
        ],
    ]
    .copy()
)

hm450_sample_index["hm450_matrix_column_index"] = (
    hm450_sample_index["hm450_matrix_column_index"].astype(np.int64)
)

hm450_sample_index = (
    hm450_sample_index
    .sort_values("hm450_matrix_column_index")
    .reset_index(drop=True)
)

if hm450_sample_index["hm450_matrix_column_index"].duplicated().any():
    raise ValueError(
        "HM450 matrix columns are not uniquely represented in the frozen sample mapping."
    )

print(
    "HM450 tumors:",
    len(hm450_sample_index),
)
print(
    "TCGA projects represented:",
    hm450_sample_index["project_id"].nunique(),
)

HM450 tumors: 8345
TCGA projects represented: 33


In [30]:
# =============================================================================
# Validate frozen HM450 sample-axis alignment
# =============================================================================

hm450_beta_values = np.load(
    upstream_artifact_paths[
        "phase2.203.final_hm450_methylation_betas"
    ],
    mmap_mode="r",
)

expected_hm450_columns = np.arange(
    hm450_beta_values.shape[1],
    dtype=np.int64,
)

sample_axis_aligned = (
    len(hm450_sample_index) == hm450_beta_values.shape[1]
    and np.array_equal(
        hm450_sample_index["hm450_matrix_column_index"].to_numpy(),
        expected_hm450_columns,
    )
)

print("HM450 beta matrix shape:", hm450_beta_values.shape)
print("HM450 sample-axis aligned:", sample_axis_aligned)

HM450 beta matrix shape: (407696, 8345)
HM450 sample-axis aligned: True


In [31]:
# =============================================================================
# Extract HM450 beta values for RNA-resolved CpGs
# =============================================================================

resolved_cpg_hm450_index = (
    rna_resolved_cpg_gene_pairs[["probe_id"]]
    .drop_duplicates()
    .merge(
        hm450_strong_probe_mapping[
            ["probe_id", "hm450_matrix_row_index"]
        ],
        on="probe_id",
        how="left",
        validate="one_to_one",
    )
    .sort_values("probe_id")
    .reset_index(drop=True)
)

resolved_hm450_row_indices = resolved_cpg_hm450_index[
    "hm450_matrix_row_index"
].to_numpy(dtype=np.int64)

resolved_hm450_betas = np.empty(
    (
        len(resolved_hm450_row_indices),
        hm450_beta_values.shape[1],
    ),
    dtype=hm450_beta_values.dtype,
)

column_chunk_size = 64

with open(hm450_beta_values.filename, "rb") as handle:
    handle.seek(hm450_beta_values.offset)

    for column_start in range(
        0,
        hm450_beta_values.shape[1],
        column_chunk_size,
    ):
        column_stop = min(
            column_start + column_chunk_size,
            hm450_beta_values.shape[1],
        )
        n_columns = column_stop - column_start

        beta_block = np.fromfile(
            handle,
            dtype=hm450_beta_values.dtype,
            count=hm450_beta_values.shape[0] * n_columns,
        ).reshape(
            hm450_beta_values.shape[0],
            n_columns,
            order="F",
        )

        resolved_hm450_betas[:, column_start:column_stop] = (
            beta_block[resolved_hm450_row_indices]
        )

print("Extracted HM450 beta matrix:", resolved_hm450_betas.shape)

Extracted HM450 beta matrix: (270, 8345)


In [32]:
# =============================================================================
# Inspect beta-value boundaries before M-value transformation
# =============================================================================

finite_beta_mask = np.isfinite(resolved_hm450_betas)

print(
    "Missing beta values:",
    int((~finite_beta_mask).sum()),
)
print(
    "Finite beta values equal to 0:",
    int((resolved_hm450_betas[finite_beta_mask] == 0).sum()),
)
print(
    "Finite beta values equal to 1:",
    int((resolved_hm450_betas[finite_beta_mask] == 1).sum()),
)
print(
    "Finite beta range:",
    (
        float(resolved_hm450_betas[finite_beta_mask].min()),
        float(resolved_hm450_betas[finite_beta_mask].max()),
    ),
)

Missing beta values: 2974
Finite beta values equal to 0: 0
Finite beta values equal to 1: 0
Finite beta range: (0.005798826459795237, 0.9951366186141968)


In [33]:
# =============================================================================
# Transform HM450 beta values to M-values
# =============================================================================

resolved_hm450_m_values = np.log2(
    resolved_hm450_betas
    / (1.0 - resolved_hm450_betas)
)

print(
    "Resolved HM450 M-value matrix:",
    resolved_hm450_m_values.shape,
)
print(
    "Missing M-values:",
    int(np.isnan(resolved_hm450_m_values).sum()),
)

Resolved HM450 M-value matrix: (270, 8345)
Missing M-values: 2974


In [34]:
# =============================================================================
# Align frozen RNA sample axis to HM450 tumors
# =============================================================================

hm450_rna_column_indices = hm450_sample_index[
    "final_sample_column_index"
].to_numpy(dtype=np.int64)

if not np.array_equal(
    hm450_sample_index["hm450_matrix_column_index"].to_numpy(),
    np.arange(len(hm450_sample_index)),
):
    raise ValueError(
        "HM450 sample order is not aligned to the frozen HM450 matrix."
    )

print(
    "HM450 tumors with RNA correspondence:",
    len(hm450_rna_column_indices),
)
print(
    "RNA column index range:",
    (
        int(hm450_rna_column_indices.min()),
        int(hm450_rna_column_indices.max()),
    ),
)

HM450 tumors with RNA correspondence: 8345
RNA column index range: (38, 9964)


In [35]:
# =============================================================================
# Construct RNA-resolved gene-axis index
# =============================================================================

resolved_rna_gene_index = (
    rna_resolved_cpg_gene_pairs[
        [
            "rna_gene_id_base",
            "rna_gene_name",
            "rna_logcpm_row_index",
        ]
    ]
    .drop_duplicates()
    .sort_values("rna_logcpm_row_index")
    .reset_index(drop=True)
)

if resolved_rna_gene_index["rna_gene_id_base"].duplicated().any():
    raise ValueError(
        "A resolved RNA gene maps to more than one expression row."
    )

print(
    "RNA-resolved genes:",
    len(resolved_rna_gene_index),
)
print(
    "RNA row index range:",
    (
        int(resolved_rna_gene_index["rna_logcpm_row_index"].min()),
        int(resolved_rna_gene_index["rna_logcpm_row_index"].max()),
    ),
)

RNA-resolved genes: 270
RNA row index range: (61, 18101)


In [36]:
# =============================================================================
# Extract RNA expression for the HM450 cohort
# =============================================================================

resolved_rna_row_indices = resolved_rna_gene_index[
    "rna_logcpm_row_index"
].to_numpy(dtype=np.int64)

with h5py.File(rna_expression_path, "r") as handle:
    resolved_rna_logcpm = np.asarray(
        handle["logcpm"][resolved_rna_row_indices, :]
    )[:, hm450_rna_column_indices]

print(
    "Resolved RNA logCPM matrix:",
    resolved_rna_logcpm.shape,
)
print(
    "Missing RNA values:",
    int(np.isnan(resolved_rna_logcpm).sum()),
)

Resolved RNA logCPM matrix: (270, 8345)
Missing RNA values: 0


In [37]:
# =============================================================================
# Link CpG-gene candidate pairs to extracted matrix rows
# =============================================================================

cpg_matrix_index = resolved_cpg_hm450_index[["probe_id"]].copy()
cpg_matrix_index["resolved_hm450_row_index"] = np.arange(
    len(cpg_matrix_index),
    dtype=np.int64,
)

rna_matrix_index = resolved_rna_gene_index[["rna_gene_id_base"]].copy()
rna_matrix_index["resolved_rna_row_index"] = np.arange(
    len(rna_matrix_index),
    dtype=np.int64,
)

cpg_gene_support_candidates = (
    rna_resolved_cpg_gene_pairs
    .merge(
        cpg_matrix_index,
        on="probe_id",
        how="left",
        validate="many_to_one",
    )
    .merge(
        rna_matrix_index,
        on="rna_gene_id_base",
        how="left",
        validate="many_to_one",
    )
)

if cpg_gene_support_candidates[
    ["resolved_hm450_row_index", "resolved_rna_row_index"]
].isna().any().any():
    raise ValueError(
        "At least one CpG-gene pair is not represented in the extracted matrices."
    )

print(
    "CpG-gene support candidates:",
    len(cpg_gene_support_candidates),
)
print(
    "Unique CpGs:",
    cpg_gene_support_candidates["probe_id"].nunique(),
)
print(
    "Unique RNA genes:",
    cpg_gene_support_candidates["rna_gene_id_base"].nunique(),
)

CpG-gene support candidates: 311
Unique CpGs: 270
Unique RNA genes: 270


In [38]:
# =============================================================================
# Evaluate project-level support for CpG-gene candidate pairs
# =============================================================================

project_column_indices = {
    project_id: group.index.to_numpy(dtype=np.int64)
    for project_id, group in hm450_sample_index.groupby(
        "project_id",
        sort=True,
    )
}

project_support_records = []

for pair in cpg_gene_support_candidates.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        pair.resolved_hm450_row_index
    ]
    expression_values = resolved_rna_logcpm[
        pair.resolved_rna_row_index
    ]

    for project_id, column_indices in project_column_indices.items():
        project_methylation = methylation_values[column_indices]
        project_expression = expression_values[column_indices]

        complete_mask = (
            np.isfinite(project_methylation)
            & np.isfinite(project_expression)
        )
        n_complete = int(complete_mask.sum())

        supported = False

        if n_complete >= 20:
            complete_methylation = project_methylation[complete_mask]
            complete_expression = project_expression[complete_mask]

            supported = (
                np.ptp(complete_methylation) > 0
                and np.ptp(complete_expression) > 0
            )

        project_support_records.append(
            {
                "probe_id": pair.probe_id,
                "rna_gene_id_base": pair.rna_gene_id_base,
                "project_id": project_id,
                "n_complete": n_complete,
                "supported": supported,
            }
        )

cpg_gene_project_support = pd.DataFrame(project_support_records)

print(
    "CpG-gene-project combinations:",
    len(cpg_gene_project_support),
)
print(
    "Supported combinations:",
    int(cpg_gene_project_support["supported"].sum()),
)

CpG-gene-project combinations: 10263
Supported combinations: 9952


In [39]:
# =============================================================================
# Define the primary CpG-gene inferential family
# =============================================================================

cpg_gene_support_summary = (
    cpg_gene_project_support
    .groupby(
        ["probe_id", "rna_gene_id_base"],
        as_index=False,
    )
    .agg(
        n_supported_projects=("supported", "sum"),
    )
)

primary_cpg_gene_family = (
    cpg_gene_support_candidates
    .merge(
        cpg_gene_support_summary,
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
    .loc[lambda df: df["n_supported_projects"] >= 3]
    .copy()
    .sort_values(["probe_id", "rna_gene_id_base"])
    .reset_index(drop=True)
)

print(
    "Candidate CpG-gene pairs:",
    len(cpg_gene_support_candidates),
)
print(
    "Primary inferential pairs:",
    len(primary_cpg_gene_family),
)
print(
    "Excluded for insufficient project support:",
    len(cpg_gene_support_candidates) - len(primary_cpg_gene_family),
)
print(
    "Supported-project range:",
    (
        int(primary_cpg_gene_family["n_supported_projects"].min()),
        int(primary_cpg_gene_family["n_supported_projects"].max()),
    ),
)

Candidate CpG-gene pairs: 311
Primary inferential pairs: 311
Excluded for insufficient project support: 0
Supported-project range: (32, 32)


In [40]:
# =============================================================================
# Characterize unsupported project-level pair combinations
# =============================================================================

unsupported_project_summary = (
    cpg_gene_project_support.loc[
        ~cpg_gene_project_support["supported"]
    ]
    .groupby("project_id", as_index=False)
    .agg(
        n_unsupported_pairs=("probe_id", "size"),
        min_complete_cases=("n_complete", "min"),
        max_complete_cases=("n_complete", "max"),
    )
    .sort_values(
        ["n_unsupported_pairs", "project_id"],
        ascending=[False, True],
    )
    .reset_index(drop=True)
)

unsupported_project_summary

,project_id,n_unsupported_pairs,min_complete_cases,max_complete_cases
0,TCGA-OV,311,6,9


In [41]:
# =============================================================================
# Construct the primary supported-project sample index
# =============================================================================

primary_supported_projects = sorted(
    cpg_gene_project_support.loc[
        cpg_gene_project_support["supported"],
        "project_id",
    ].unique()
)

primary_sample_mask = hm450_sample_index[
    "project_id"
].isin(primary_supported_projects).to_numpy()

primary_sample_index = (
    hm450_sample_index.loc[primary_sample_mask]
    .reset_index(drop=True)
)

print(
    "Primary supported projects:",
    len(primary_supported_projects),
)
print(
    "Primary HM450 tumors:",
    len(primary_sample_index),
)
print(
    "Excluded HM450 tumors:",
    len(hm450_sample_index) - len(primary_sample_index),
)

Primary supported projects: 32
Primary HM450 tumors: 8336
Excluded HM450 tumors: 9


In [42]:
# =============================================================================
# Construct project fixed-effect design
# =============================================================================

primary_project = pd.Categorical(
    primary_sample_index["project_id"],
    categories=primary_supported_projects,
    ordered=True,
)

project_design = pd.get_dummies(
    primary_project,
    drop_first=True,
    dtype=float,
)

project_design.insert(0, "intercept", 1.0)

primary_column_indices = np.flatnonzero(primary_sample_mask)

print(
    "Primary design samples:",
    len(project_design),
)
print(
    "Project fixed-effect columns:",
    project_design.shape[1],
)
print(
    "Reference project:",
    primary_supported_projects[0],
)

Primary design samples: 8336
Project fixed-effect columns: 32
Reference project: TCGA-ACC


In [43]:
# =============================================================================
# Validate the primary model on one CpG-gene pair
# =============================================================================

validation_pair = primary_cpg_gene_family.iloc[0]

methylation_values = resolved_hm450_m_values[
    int(validation_pair["resolved_hm450_row_index"]),
    primary_column_indices,
]

expression_values = resolved_rna_logcpm[
    int(validation_pair["resolved_rna_row_index"]),
    primary_column_indices,
]

complete_mask = (
    np.isfinite(methylation_values)
    & np.isfinite(expression_values)
)

validation_design = project_design.loc[complete_mask].copy()
validation_design["cpg_methylation"] = methylation_values[complete_mask]

validation_model = sm.OLS(
    expression_values[complete_mask],
    validation_design,
).fit(cov_type="HC3")

confidence_interval = validation_model.conf_int().loc[
    "cpg_methylation"
]

print(
    "CpG-gene pair:",
    validation_pair["probe_id"],
    validation_pair["rna_gene_id_base"],
)
print("Complete cases:", int(complete_mask.sum()))
print(
    "Methylation coefficient:",
    float(validation_model.params["cpg_methylation"]),
)
print(
    "HC3 standard error:",
    float(validation_model.bse["cpg_methylation"]),
)
print(
    "95% CI:",
    (
        float(confidence_interval.iloc[0]),
        float(confidence_interval.iloc[1]),
    ),
)
print(
    "Test statistic:",
    float(validation_model.tvalues["cpg_methylation"]),
)
print(
    "P-value:",
    float(validation_model.pvalues["cpg_methylation"]),
)

CpG-gene pair: cg00041575 ENSG00000064201
Complete cases: 8333
Methylation coefficient: -0.08433187570834218
HC3 standard error: 0.01081326960961369
95% CI: (-0.1055254946983065, -0.06313825671837786)
Test statistic: -7.798924724244897
P-value: 6.243689280573499e-15


In [44]:
# =============================================================================
# Fit primary CpG-gene association models
# =============================================================================

primary_model_records = []

for pair in primary_cpg_gene_family.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        pair.resolved_hm450_row_index,
        primary_column_indices,
    ]
    expression_values = resolved_rna_logcpm[
        pair.resolved_rna_row_index,
        primary_column_indices,
    ]

    complete_mask = (
        np.isfinite(methylation_values)
        & np.isfinite(expression_values)
    )

    model_design = project_design.loc[complete_mask].copy()
    model_design["cpg_methylation"] = methylation_values[complete_mask]

    model = sm.OLS(
        expression_values[complete_mask],
        model_design,
    ).fit(cov_type="HC3")

    confidence_interval = model.conf_int().loc["cpg_methylation"]

    primary_model_records.append(
        {
            "probe_id": pair.probe_id,
            "rna_gene_id_base": pair.rna_gene_id_base,
            "n_complete": int(complete_mask.sum()),
            "n_supported_projects": int(pair.n_supported_projects),
            "methylation_coefficient": float(
                model.params["cpg_methylation"]
            ),
            "hc3_standard_error": float(
                model.bse["cpg_methylation"]
            ),
            "ci_95_lower": float(confidence_interval.iloc[0]),
            "ci_95_upper": float(confidence_interval.iloc[1]),
            "test_statistic": float(
                model.tvalues["cpg_methylation"]
            ),
            "p_value": float(
                model.pvalues["cpg_methylation"]
            ),
        }
    )

primary_model_results = pd.DataFrame(primary_model_records)

print(
    "Primary models fitted:",
    len(primary_model_results),
)
print(
    "Complete-case range:",
    (
        int(primary_model_results["n_complete"].min()),
        int(primary_model_results["n_complete"].max()),
    ),
)
print(
    "Nominal p-value range:",
    (
        float(primary_model_results["p_value"].min()),
        float(primary_model_results["p_value"].max()),
    ),
)

Primary models fitted: 311
Complete-case range: (8001, 8336)
Nominal p-value range: (0.0, 0.7128580361057827)


In [45]:
# =============================================================================
# Apply global Benjamini-Hochberg correction
# =============================================================================

fdr_reject, q_values, _, _ = sm.stats.multipletests(
    primary_model_results["p_value"].to_numpy(),
    alpha=0.05,
    method="fdr_bh",
)

primary_model_results["q_value"] = q_values
primary_model_results["primary_fdr_supported"] = fdr_reject

print(
    "Primary hypothesis tests:",
    len(primary_model_results),
)
print(
    "FDR-supported associations:",
    int(primary_model_results["primary_fdr_supported"].sum()),
)
print(
    "Q-value range:",
    (
        float(primary_model_results["q_value"].min()),
        float(primary_model_results["q_value"].max()),
    ),
)
print(
    "Numerically zero p-values:",
    int(primary_model_results["p_value"].eq(0.0).sum()),
)

Primary hypothesis tests: 311
FDR-supported associations: 289
Q-value range: (0.0, 0.7128580361057827)
Numerically zero p-values: 41


In [46]:
# =============================================================================
# Define primary FDR-supported associations
# =============================================================================

primary_fdr_associations = (
    primary_cpg_gene_family
    .merge(
        primary_model_results,
        on=[
            "probe_id",
            "rna_gene_id_base",
            "n_supported_projects",
        ],
        how="inner",
        validate="one_to_one",
    )
    .loc[lambda df: df["primary_fdr_supported"]]
    .copy()
    .sort_values(["probe_id", "rna_gene_id_base"])
    .reset_index(drop=True)
)

print(
    "Primary FDR-supported associations:",
    len(primary_fdr_associations),
)
print(
    "Inverse associations:",
    int(
        primary_fdr_associations[
            "methylation_coefficient"
        ].lt(0).sum()
    ),
)
print(
    "Positive associations:",
    int(
        primary_fdr_associations[
            "methylation_coefficient"
        ].gt(0).sum()
    ),
)

Primary FDR-supported associations: 289
Inverse associations: 235
Positive associations: 54


In [47]:
# =============================================================================
# Estimate within-project CpG-gene associations
# =============================================================================

supported_projects_by_pair = (
    cpg_gene_project_support.loc[
        cpg_gene_project_support["supported"]
    ]
    .groupby(["probe_id", "rna_gene_id_base"])["project_id"]
    .apply(list)
    .to_dict()
)

within_project_records = []

for pair in primary_fdr_associations.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        int(pair.resolved_hm450_row_index)
    ]
    expression_values = resolved_rna_logcpm[
        int(pair.resolved_rna_row_index)
    ]

    pair_key = (
        pair.probe_id,
        pair.rna_gene_id_base,
    )

    for project_id in supported_projects_by_pair[pair_key]:
        column_indices = project_column_indices[project_id]

        project_methylation = methylation_values[column_indices]
        project_expression = expression_values[column_indices]

        complete_mask = (
            np.isfinite(project_methylation)
            & np.isfinite(project_expression)
        )

        model_design = sm.add_constant(
            project_methylation[complete_mask],
            has_constant="add",
        )

        model = sm.OLS(
            project_expression[complete_mask],
            model_design,
        ).fit()

        within_project_records.append(
            {
                "probe_id": pair.probe_id,
                "rna_gene_id_base": pair.rna_gene_id_base,
                "project_id": project_id,
                "n_complete": int(complete_mask.sum()),
                "methylation_coefficient": float(model.params[1]),
            }
        )

within_project_results = pd.DataFrame(within_project_records)

project_counts = (
    within_project_results
    .groupby(["probe_id", "rna_gene_id_base"])
    .size()
)

print(
    "Within-project associations:",
    len(within_project_results),
)
print(
    "Projects per FDR-supported association:",
    (
        int(project_counts.min()),
        int(project_counts.max()),
    ),
)

Within-project associations: 9248
Projects per FDR-supported association: (32, 32)


In [48]:
# =============================================================================
# Summarize cross-project directional concordance
# =============================================================================

pooled_direction = (
    primary_fdr_associations[
        [
            "probe_id",
            "rna_gene_id_base",
            "methylation_coefficient",
        ]
    ]
    .rename(
        columns={
            "methylation_coefficient": "pooled_methylation_coefficient"
        }
    )
)

within_project_direction = (
    within_project_results
    .merge(
        pooled_direction,
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="many_to_one",
    )
)

within_project_direction["same_pooled_direction"] = (
    np.sign(within_project_direction["methylation_coefficient"])
    == np.sign(
        within_project_direction["pooled_methylation_coefficient"]
    )
)

directional_concordance = (
    within_project_direction
    .groupby(
        ["probe_id", "rna_gene_id_base"],
        as_index=False,
    )
    .agg(
        n_supported_projects=("project_id", "size"),
        n_same_direction_projects=("same_pooled_direction", "sum"),
    )
)

directional_concordance["directional_concordance_fraction"] = (
    directional_concordance["n_same_direction_projects"]
    / directional_concordance["n_supported_projects"]
)

directional_concordance["passes_directional_criteria"] = (
    directional_concordance["n_same_direction_projects"].ge(3)
    & directional_concordance[
        "directional_concordance_fraction"
    ].ge(0.70)
)

print(
    "FDR-supported associations:",
    len(directional_concordance),
)
print(
    "Passing directional criteria:",
    int(
        directional_concordance[
            "passes_directional_criteria"
        ].sum()
    ),
)
print(
    "Directional concordance range:",
    (
        float(
            directional_concordance[
                "directional_concordance_fraction"
            ].min()
        ),
        float(
            directional_concordance[
                "directional_concordance_fraction"
            ].max()
        ),
    ),
)

FDR-supported associations: 289
Passing directional criteria: 223
Directional concordance range: (0.3125, 1.0)


In [49]:
# =============================================================================
# Validate fixed-effect residualization against the primary model
# =============================================================================

validation_pair = primary_fdr_associations.iloc[0]

methylation_values = resolved_hm450_m_values[
    int(validation_pair["resolved_hm450_row_index"]),
    primary_column_indices,
]

expression_values = resolved_rna_logcpm[
    int(validation_pair["resolved_rna_row_index"]),
    primary_column_indices,
]

complete_mask = (
    np.isfinite(methylation_values)
    & np.isfinite(expression_values)
)

validation_data = pd.DataFrame(
    {
        "methylation": methylation_values[complete_mask],
        "expression": expression_values[complete_mask],
        "project_id": primary_sample_index.loc[
            complete_mask,
            "project_id",
        ].to_numpy(),
    }
)

validation_data["methylation_centered"] = (
    validation_data["methylation"]
    - validation_data.groupby("project_id")["methylation"].transform("mean")
)

validation_data["expression_centered"] = (
    validation_data["expression"]
    - validation_data.groupby("project_id")["expression"].transform("mean")
)

residualized_coefficient = (
    np.dot(
        validation_data["methylation_centered"],
        validation_data["expression_centered"],
    )
    / np.dot(
        validation_data["methylation_centered"],
        validation_data["methylation_centered"],
    )
)

primary_coefficient = validation_pair["methylation_coefficient"]

print(
    "Primary-model coefficient:",
    float(primary_coefficient),
)
print(
    "Residualized coefficient:",
    float(residualized_coefficient),
)
print(
    "Absolute difference:",
    float(abs(primary_coefficient - residualized_coefficient)),
)

Primary-model coefficient: -0.08433187570834218
Residualized coefficient: -0.08433187440631766
Absolute difference: 1.3020245159811594e-09


In [50]:
# =============================================================================
# Perform leave-one-project-out coefficient estimation
# =============================================================================

lopo_records = []

for pair in primary_fdr_associations.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        int(pair.resolved_hm450_row_index)
    ]
    expression_values = resolved_rna_logcpm[
        int(pair.resolved_rna_row_index)
    ]

    pair_key = (
        pair.probe_id,
        pair.rna_gene_id_base,
    )

    project_sums = []

    for project_id in supported_projects_by_pair[pair_key]:
        column_indices = project_column_indices[project_id]

        project_methylation = methylation_values[column_indices]
        project_expression = expression_values[column_indices]

        complete_mask = (
            np.isfinite(project_methylation)
            & np.isfinite(project_expression)
        )

        x = project_methylation[complete_mask]
        y = project_expression[complete_mask]

        x_centered = x - x.mean()
        y_centered = y - y.mean()

        project_sums.append(
            {
                "project_id": project_id,
                "n_complete": int(complete_mask.sum()),
                "sxx": float(np.dot(x_centered, x_centered)),
                "sxy": float(np.dot(x_centered, y_centered)),
            }
        )

    total_sxx = sum(item["sxx"] for item in project_sums)
    total_sxy = sum(item["sxy"] for item in project_sums)
    total_n = sum(item["n_complete"] for item in project_sums)

    for omitted in project_sums:
        lopo_coefficient = (
            (total_sxy - omitted["sxy"])
            / (total_sxx - omitted["sxx"])
        )

        lopo_records.append(
            {
                "probe_id": pair.probe_id,
                "rna_gene_id_base": pair.rna_gene_id_base,
                "omitted_project_id": omitted["project_id"],
                "n_complete": total_n - omitted["n_complete"],
                "lopo_methylation_coefficient": lopo_coefficient,
                "sign_reversal": (
                    lopo_coefficient
                    * pair.methylation_coefficient
                    < 0
                ),
            }
        )

lopo_results = pd.DataFrame(lopo_records)

print(
    "LOPO refits:",
    len(lopo_results),
)
print(
    "Associations with >=1 sign reversal:",
    int(
        lopo_results
        .groupby(["probe_id", "rna_gene_id_base"])["sign_reversal"]
        .any()
        .sum()
    ),
)
print(
    "Minimum absolute LOPO coefficient:",
    float(
        lopo_results["lopo_methylation_coefficient"]
        .abs()
        .min()
    ),
)

LOPO refits: 9248
Associations with >=1 sign reversal: 2
Minimum absolute LOPO coefficient: 0.002445525602730746


In [51]:
# =============================================================================
# Classify cross-project recurrent associations
# =============================================================================

lopo_summary = (
    lopo_results
    .groupby(
        ["probe_id", "rna_gene_id_base"],
        as_index=False,
    )
    .agg(
        any_lopo_sign_reversal=("sign_reversal", "any"),
    )
)

recurrence_summary = (
    primary_fdr_associations[
        [
            "probe_id",
            "rna_gene_id_base",
            "n_supported_projects",
            "methylation_coefficient",
            "q_value",
        ]
    ]
    .merge(
        directional_concordance,
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
        suffixes=("", "_directional"),
    )
    .merge(
        lopo_summary,
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
)

recurrence_summary["cross_project_recurrent"] = (
    recurrence_summary["q_value"].lt(0.05)
    & recurrence_summary["n_supported_projects"].ge(3)
    & recurrence_summary["n_same_direction_projects"].ge(3)
    & recurrence_summary["directional_concordance_fraction"].ge(0.70)
    & ~recurrence_summary["any_lopo_sign_reversal"]
)

print(
    "FDR-supported associations:",
    len(recurrence_summary),
)
print(
    "Cross-project recurrent associations:",
    int(recurrence_summary["cross_project_recurrent"].sum()),
)
print(
    "Directional-pass associations with LOPO reversal:",
    int(
        (
            recurrence_summary["passes_directional_criteria"]
            & recurrence_summary["any_lopo_sign_reversal"]
        ).sum()
    ),
)
print(
    "Non-recurrent associations:",
    int((~recurrence_summary["cross_project_recurrent"]).sum()),
)

FDR-supported associations: 289
Cross-project recurrent associations: 223
Directional-pass associations with LOPO reversal: 0
Non-recurrent associations: 66


In [52]:
# =============================================================================
# Consolidate cross-project recurrence with primary associations
# =============================================================================

recurrence_metrics = recurrence_summary[
    [
        "probe_id",
        "rna_gene_id_base",
        "n_same_direction_projects",
        "directional_concordance_fraction",
        "any_lopo_sign_reversal",
        "cross_project_recurrent",
    ]
]

primary_fdr_characterization = (
    primary_fdr_associations
    .merge(
        recurrence_metrics,
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
)

primary_recurrent_associations = (
    primary_fdr_characterization
    .loc[lambda df: df["cross_project_recurrent"]]
    .copy()
    .sort_values(["probe_id", "rna_gene_id_base"])
    .reset_index(drop=True)
)

print(
    "Cross-project recurrent associations:",
    len(primary_recurrent_associations),
)
print(
    "Recurrent inverse associations:",
    int(
        primary_recurrent_associations[
            "methylation_coefficient"
        ].lt(0).sum()
    ),
)
print(
    "Recurrent positive associations:",
    int(
        primary_recurrent_associations[
            "methylation_coefficient"
        ].gt(0).sum()
    ),
)

Cross-project recurrent associations: 223
Recurrent inverse associations: 195
Recurrent positive associations: 28


In [53]:
# =============================================================================
# Annotate promoter-associated inverse recurrent relationships
# =============================================================================

primary_recurrent_associations[
    "promoter_associated_inverse_relationship"
] = (
    primary_recurrent_associations["promoter_associated"]
    & primary_recurrent_associations["methylation_coefficient"].lt(0)
)

print(
    "Cross-project recurrent associations:",
    len(primary_recurrent_associations),
)
print(
    "Promoter-associated recurrent associations:",
    int(
        primary_recurrent_associations[
            "promoter_associated"
        ].sum()
    ),
)
print(
    "Promoter-associated inverse recurrent relationships:",
    int(
        primary_recurrent_associations[
            "promoter_associated_inverse_relationship"
        ].sum()
    ),
)

Cross-project recurrent associations: 223
Promoter-associated recurrent associations: 210
Promoter-associated inverse recurrent relationships: 192


In [54]:
# =============================================================================
# Attach frozen methylation-component and consensus-program context
# =============================================================================

recurrent_program_context = (
    primary_recurrent_associations[
        [
            "probe_id",
            "rna_gene_id_base",
            "methylation_coefficient",
            "q_value",
            "promoter_associated",
            "promoter_associated_inverse_relationship",
        ]
    ]
    .merge(
        strong_loading_cpg_memberships[
            [
                "probe_id",
                "methylation_component",
                "loading",
                "loading_tail",
            ]
        ],
        on="probe_id",
        how="left",
        validate="many_to_many",
    )
    .merge(
        methylation_component_context[
            [
                "methylation_component",
                "consensus_program_id",
                "candidate_pair",
                "rna_component",
            ]
        ],
        on="methylation_component",
        how="left",
        validate="many_to_many",
    )
    .drop_duplicates()
    .sort_values(
        [
            "consensus_program_id",
            "methylation_component",
            "probe_id",
            "rna_gene_id_base",
        ]
    )
    .reset_index(drop=True)
)

print(
    "Contextual rows:",
    len(recurrent_program_context),
)
print(
    "Unique recurrent CpG-gene associations:",
    recurrent_program_context[
        ["probe_id", "rna_gene_id_base"]
    ].drop_duplicates().shape[0],
)
print(
    "Methylation components represented:",
    recurrent_program_context["methylation_component"].nunique(),
)
print(
    "Consensus programs represented:",
    recurrent_program_context["consensus_program_id"].nunique(),
)

Contextual rows: 332
Unique recurrent CpG-gene associations: 223
Methylation components represented: 3
Consensus programs represented: 3


In [55]:
# =============================================================================
# Align frozen sensitivity covariates to the primary HM450 sample axis
# =============================================================================

primary_sensitivity_covariates = (
    primary_sample_index[
        [
            "final_sample_column_index",
            "case_submitter_id",
            "project_id",
        ]
    ]
    .merge(
        confounder_covariates[
            [
                "final_sample_column_index",
                "absolute_purity",
                "external_panimmune_proliferation_score",
                "leukocyte_fraction",
            ]
        ],
        on="final_sample_column_index",
        how="left",
        validate="one_to_one",
    )
)

print(
    "Primary sensitivity samples:",
    len(primary_sensitivity_covariates),
)
print(
    "Absolute purity available:",
    int(primary_sensitivity_covariates["absolute_purity"].notna().sum()),
)
print(
    "Proliferation score available:",
    int(
        primary_sensitivity_covariates[
            "external_panimmune_proliferation_score"
        ].notna().sum()
    ),
)
print(
    "Leukocyte fraction available:",
    int(
        primary_sensitivity_covariates[
            "leukocyte_fraction"
        ].notna().sum()
    ),
)

Primary sensitivity samples: 8336
Absolute purity available: 7952
Proliferation score available: 7666
Leukocyte fraction available: 8002


In [56]:
# =============================================================================
# Fit tumor-purity sensitivity models
# =============================================================================

absolute_purity = primary_sensitivity_covariates[
    "absolute_purity"
].to_numpy(dtype=float)

purity_sensitivity_records = []

for pair in primary_fdr_associations.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        int(pair.resolved_hm450_row_index),
        primary_column_indices,
    ]
    expression_values = resolved_rna_logcpm[
        int(pair.resolved_rna_row_index),
        primary_column_indices,
    ]

    complete_mask = (
        np.isfinite(methylation_values)
        & np.isfinite(expression_values)
        & np.isfinite(absolute_purity)
    )

    x = methylation_values[complete_mask]
    y = expression_values[complete_mask]
    purity = absolute_purity[complete_mask]
    projects = primary_sample_index.loc[
        complete_mask,
        "project_id",
    ].to_numpy()

    n_supported_projects = 0

    for project_id in np.unique(projects):
        project_mask = projects == project_id

        if (
            project_mask.sum() >= 20
            and np.ptp(x[project_mask]) > 0
            and np.ptp(y[project_mask]) > 0
        ):
            n_supported_projects += 1

    model_design = pd.get_dummies(
        pd.Categorical(projects),
        drop_first=True,
        dtype=float,
    )
    model_design.insert(0, "intercept", 1.0)
    model_design["cpg_methylation"] = x
    model_design["absolute_purity"] = purity

    model = sm.OLS(
        y,
        model_design,
    ).fit(cov_type="HC3")

    confidence_interval = model.conf_int().loc[
        "cpg_methylation"
    ]

    purity_coefficient = float(
        model.params["cpg_methylation"]
    )
    primary_coefficient = float(
        pair.methylation_coefficient
    )

    purity_sensitivity_records.append(
        {
            "probe_id": pair.probe_id,
            "rna_gene_id_base": pair.rna_gene_id_base,
            "n_complete": int(complete_mask.sum()),
            "n_supported_projects": n_supported_projects,
            "methylation_coefficient": purity_coefficient,
            "hc3_standard_error": float(
                model.bse["cpg_methylation"]
            ),
            "ci_95_lower": float(confidence_interval.iloc[0]),
            "ci_95_upper": float(confidence_interval.iloc[1]),
            "direction_preserved": (
                np.sign(purity_coefficient)
                == np.sign(primary_coefficient)
            ),
            "magnitude_ratio_to_primary": (
                abs(purity_coefficient)
                / abs(primary_coefficient)
            ),
        }
    )

purity_sensitivity_results = pd.DataFrame(
    purity_sensitivity_records
)

print(
    "Purity sensitivity models:",
    len(purity_sensitivity_results),
)
print(
    "Complete-case range:",
    (
        int(purity_sensitivity_results["n_complete"].min()),
        int(purity_sensitivity_results["n_complete"].max()),
    ),
)
print(
    "Supported-project range:",
    (
        int(
            purity_sensitivity_results[
                "n_supported_projects"
            ].min()
        ),
        int(
            purity_sensitivity_results[
                "n_supported_projects"
            ].max()
        ),
    ),
)
print(
    "Direction preserved:",
    int(
        purity_sensitivity_results[
            "direction_preserved"
        ].sum()
    ),
)

Purity sensitivity models: 289
Complete-case range: (7638, 7952)
Supported-project range: (32, 32)
Direction preserved: 286


In [57]:
# =============================================================================
# Fit proliferation sensitivity models
# =============================================================================

proliferation_score = primary_sensitivity_covariates[
    "external_panimmune_proliferation_score"
].to_numpy(dtype=float)

proliferation_sensitivity_records = []

for pair in primary_fdr_associations.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        int(pair.resolved_hm450_row_index),
        primary_column_indices,
    ]
    expression_values = resolved_rna_logcpm[
        int(pair.resolved_rna_row_index),
        primary_column_indices,
    ]

    complete_mask = (
        np.isfinite(methylation_values)
        & np.isfinite(expression_values)
        & np.isfinite(proliferation_score)
    )

    x = methylation_values[complete_mask]
    y = expression_values[complete_mask]
    proliferation = proliferation_score[complete_mask]
    projects = primary_sample_index.loc[
        complete_mask,
        "project_id",
    ].to_numpy()

    n_supported_projects = sum(
        (
            (projects == project_id).sum() >= 20
            and np.ptp(x[projects == project_id]) > 0
            and np.ptp(y[projects == project_id]) > 0
        )
        for project_id in np.unique(projects)
    )

    model_design = project_design.loc[complete_mask].copy()
    model_design["cpg_methylation"] = x
    model_design["proliferation_score"] = proliferation

    model = sm.OLS(
        y,
        model_design,
    ).fit(cov_type="HC3")

    confidence_interval = model.conf_int().loc["cpg_methylation"]

    sensitivity_coefficient = float(
        model.params["cpg_methylation"]
    )
    primary_coefficient = float(
        pair.methylation_coefficient
    )

    proliferation_sensitivity_records.append(
        {
            "probe_id": pair.probe_id,
            "rna_gene_id_base": pair.rna_gene_id_base,
            "n_complete": int(complete_mask.sum()),
            "n_supported_projects": int(n_supported_projects),
            "methylation_coefficient": sensitivity_coefficient,
            "hc3_standard_error": float(
                model.bse["cpg_methylation"]
            ),
            "ci_95_lower": float(confidence_interval.iloc[0]),
            "ci_95_upper": float(confidence_interval.iloc[1]),
            "direction_preserved": (
                np.sign(sensitivity_coefficient)
                == np.sign(primary_coefficient)
            ),
            "magnitude_ratio_to_primary": (
                abs(sensitivity_coefficient)
                / abs(primary_coefficient)
            ),
        }
    )

proliferation_sensitivity_results = pd.DataFrame(
    proliferation_sensitivity_records
)

print(
    "Proliferation sensitivity models:",
    len(proliferation_sensitivity_results),
)
print(
    "Complete-case range:",
    (
        int(proliferation_sensitivity_results["n_complete"].min()),
        int(proliferation_sensitivity_results["n_complete"].max()),
    ),
)
print(
    "Supported-project range:",
    (
        int(
            proliferation_sensitivity_results[
                "n_supported_projects"
            ].min()
        ),
        int(
            proliferation_sensitivity_results[
                "n_supported_projects"
            ].max()
        ),
    ),
)
print(
    "Direction preserved:",
    int(
        proliferation_sensitivity_results[
            "direction_preserved"
        ].sum()
    ),
)

Proliferation sensitivity models: 289
Complete-case range: (7357, 7666)
Supported-project range: (29, 29)
Direction preserved: 288


In [58]:
# =============================================================================
# Fit proliferation sensitivity models
# =============================================================================

proliferation_score = primary_sensitivity_covariates[
    "external_panimmune_proliferation_score"
].to_numpy(dtype=float)

proliferation_sensitivity_records = []

for pair in primary_fdr_associations.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        int(pair.resolved_hm450_row_index),
        primary_column_indices,
    ]
    expression_values = resolved_rna_logcpm[
        int(pair.resolved_rna_row_index),
        primary_column_indices,
    ]

    complete_mask = (
        np.isfinite(methylation_values)
        & np.isfinite(expression_values)
        & np.isfinite(proliferation_score)
    )

    x = methylation_values[complete_mask]
    y = expression_values[complete_mask]
    proliferation = proliferation_score[complete_mask]
    projects = primary_sample_index.loc[
        complete_mask,
        "project_id",
    ].to_numpy()

    n_supported_projects = sum(
        (
            (projects == project_id).sum() >= 20
            and np.ptp(x[projects == project_id]) > 0
            and np.ptp(y[projects == project_id]) > 0
        )
        for project_id in np.unique(projects)
    )

    model_design = project_design.loc[complete_mask].copy()
    model_design["cpg_methylation"] = x
    model_design["proliferation_score"] = proliferation

    model = sm.OLS(
        y,
        model_design,
    ).fit(cov_type="HC3")

    confidence_interval = model.conf_int().loc["cpg_methylation"]

    sensitivity_coefficient = float(
        model.params["cpg_methylation"]
    )
    primary_coefficient = float(
        pair.methylation_coefficient
    )

    proliferation_sensitivity_records.append(
        {
            "probe_id": pair.probe_id,
            "rna_gene_id_base": pair.rna_gene_id_base,
            "n_complete": int(complete_mask.sum()),
            "n_supported_projects": int(n_supported_projects),
            "methylation_coefficient": sensitivity_coefficient,
            "hc3_standard_error": float(
                model.bse["cpg_methylation"]
            ),
            "ci_95_lower": float(confidence_interval.iloc[0]),
            "ci_95_upper": float(confidence_interval.iloc[1]),
            "direction_preserved": (
                np.sign(sensitivity_coefficient)
                == np.sign(primary_coefficient)
            ),
            "magnitude_ratio_to_primary": (
                abs(sensitivity_coefficient)
                / abs(primary_coefficient)
            ),
        }
    )

proliferation_sensitivity_results = pd.DataFrame(
    proliferation_sensitivity_records
)

print(
    "Proliferation sensitivity models:",
    len(proliferation_sensitivity_results),
)
print(
    "Complete-case range:",
    (
        int(proliferation_sensitivity_results["n_complete"].min()),
        int(proliferation_sensitivity_results["n_complete"].max()),
    ),
)
print(
    "Supported-project range:",
    (
        int(
            proliferation_sensitivity_results[
                "n_supported_projects"
            ].min()
        ),
        int(
            proliferation_sensitivity_results[
                "n_supported_projects"
            ].max()
        ),
    ),
)
print(
    "Direction preserved:",
    int(
        proliferation_sensitivity_results[
            "direction_preserved"
        ].sum()
    ),
)

Proliferation sensitivity models: 289
Complete-case range: (7357, 7666)
Supported-project range: (29, 29)
Direction preserved: 288


In [59]:
# =============================================================================
# Define METH_IC128 associations for leukocyte-fraction sensitivity
# =============================================================================

meth_ic128_cpgs = set(
    strong_loading_cpg_memberships.loc[
        strong_loading_cpg_memberships[
            "methylation_component"
        ].eq("METH_IC128"),
        "probe_id",
    ]
)

meth_ic128_fdr_associations = (
    primary_fdr_associations.loc[
        primary_fdr_associations["probe_id"].isin(
            meth_ic128_cpgs
        )
    ]
    .copy()
    .sort_values(["probe_id", "rna_gene_id_base"])
    .reset_index(drop=True)
)

print(
    "METH_IC128 FDR-supported associations:",
    len(meth_ic128_fdr_associations),
)
print(
    "Unique METH_IC128 CpGs:",
    meth_ic128_fdr_associations["probe_id"].nunique(),
)
print(
    "Cross-project recurrent within METH_IC128:",
    int(
        meth_ic128_fdr_associations[
            ["probe_id", "rna_gene_id_base"]
        ]
        .merge(
            recurrence_summary[
                [
                    "probe_id",
                    "rna_gene_id_base",
                    "cross_project_recurrent",
                ]
            ],
            on=["probe_id", "rna_gene_id_base"],
            how="left",
            validate="one_to_one",
        )["cross_project_recurrent"]
        .sum()
    ),
)

METH_IC128 FDR-supported associations: 105
Unique METH_IC128 CpGs: 95
Cross-project recurrent within METH_IC128: 93


In [60]:
# =============================================================================
# Fit leukocyte-fraction sensitivity models for METH_IC128
# =============================================================================

leukocyte_fraction = primary_sensitivity_covariates[
    "leukocyte_fraction"
].to_numpy(dtype=float)

leukocyte_sensitivity_records = []

for pair in meth_ic128_fdr_associations.itertuples(index=False):
    methylation_values = resolved_hm450_m_values[
        int(pair.resolved_hm450_row_index),
        primary_column_indices,
    ]
    expression_values = resolved_rna_logcpm[
        int(pair.resolved_rna_row_index),
        primary_column_indices,
    ]

    complete_mask = (
        np.isfinite(methylation_values)
        & np.isfinite(expression_values)
        & np.isfinite(leukocyte_fraction)
    )

    x = methylation_values[complete_mask]
    y = expression_values[complete_mask]
    leukocyte = leukocyte_fraction[complete_mask]
    projects = primary_sample_index.loc[
        complete_mask,
        "project_id",
    ].to_numpy()

    n_supported_projects = sum(
        (
            (projects == project_id).sum() >= 20
            and np.ptp(x[projects == project_id]) > 0
            and np.ptp(y[projects == project_id]) > 0
        )
        for project_id in np.unique(projects)
    )

    model_design = project_design.loc[complete_mask].copy()
    model_design["cpg_methylation"] = x
    model_design["leukocyte_fraction"] = leukocyte

    model = sm.OLS(
        y,
        model_design,
    ).fit(cov_type="HC3")

    confidence_interval = model.conf_int().loc["cpg_methylation"]

    sensitivity_coefficient = float(
        model.params["cpg_methylation"]
    )
    primary_coefficient = float(
        pair.methylation_coefficient
    )

    leukocyte_sensitivity_records.append(
        {
            "probe_id": pair.probe_id,
            "rna_gene_id_base": pair.rna_gene_id_base,
            "n_complete": int(complete_mask.sum()),
            "n_supported_projects": int(n_supported_projects),
            "methylation_coefficient": sensitivity_coefficient,
            "hc3_standard_error": float(
                model.bse["cpg_methylation"]
            ),
            "ci_95_lower": float(confidence_interval.iloc[0]),
            "ci_95_upper": float(confidence_interval.iloc[1]),
            "direction_preserved": (
                np.sign(sensitivity_coefficient)
                == np.sign(primary_coefficient)
            ),
            "magnitude_ratio_to_primary": (
                abs(sensitivity_coefficient)
                / abs(primary_coefficient)
            ),
        }
    )

leukocyte_sensitivity_results = pd.DataFrame(
    leukocyte_sensitivity_records
)

print(
    "Leukocyte sensitivity models:",
    len(leukocyte_sensitivity_results),
)
print(
    "Complete-case range:",
    (
        int(leukocyte_sensitivity_results["n_complete"].min()),
        int(leukocyte_sensitivity_results["n_complete"].max()),
    ),
)
print(
    "Supported-project range:",
    (
        int(
            leukocyte_sensitivity_results[
                "n_supported_projects"
            ].min()
        ),
        int(
            leukocyte_sensitivity_results[
                "n_supported_projects"
            ].max()
        ),
    ),
)
print(
    "Direction preserved:",
    int(
        leukocyte_sensitivity_results[
            "direction_preserved"
        ].sum()
    ),
)

Leukocyte sensitivity models: 105
Complete-case range: (7684, 8002)
Supported-project range: (29, 29)
Direction preserved: 93


In [61]:
# =============================================================================
# Identify HM27-covered primary FDR-supported associations
# =============================================================================

hm27_probe_index = (
    probe_mapping.loc[
        probe_mapping["representation"].eq("hm27"),
        ["probe_id", "matrix_row_index"],
    ]
    .rename(
        columns={
            "matrix_row_index": "hm27_matrix_row_index",
        }
    )
    .drop_duplicates("probe_id")
)

hm27_covered_fdr_associations = (
    primary_fdr_associations
    .merge(
        hm27_probe_index,
        on="probe_id",
        how="left",
        validate="many_to_one",
    )
    .loc[lambda df: df["hm27_matrix_row_index"].notna()]
    .copy()
    .sort_values(["probe_id", "rna_gene_id_base"])
    .reset_index(drop=True)
)

print(
    "Primary FDR-supported associations:",
    len(primary_fdr_associations),
)
print(
    "HM27-covered associations:",
    len(hm27_covered_fdr_associations),
)
print(
    "Unique HM27-covered CpGs:",
    hm27_covered_fdr_associations["probe_id"].nunique(),
)

Primary FDR-supported associations: 289
HM27-covered associations: 289
Unique HM27-covered CpGs: 257


In [62]:
# =============================================================================
# Construct the HM27 sample index
# =============================================================================

hm27_sample_index = (
    sample_mapping.loc[
        sample_mapping["hm27_matrix_column_index"].notna(),
        [
            "final_sample_column_index",
            "case_submitter_id",
            "project_id",
            "hm27_matrix_column_index",
        ],
    ]
    .sort_values("hm27_matrix_column_index")
    .reset_index(drop=True)
)

print(
    "HM27 tumors:",
    len(hm27_sample_index),
)
print(
    "TCGA projects represented:",
    hm27_sample_index["project_id"].nunique(),
)
print(
    "HM27 matrix-column range:",
    (
        int(hm27_sample_index["hm27_matrix_column_index"].min()),
        int(hm27_sample_index["hm27_matrix_column_index"].max()),
    ),
)

HM27 tumors: 1620
TCGA projects represented: 11
HM27 matrix-column range: (0, 1619)


In [63]:
# =============================================================================
# Load the frozen HM27 methylation matrix
# =============================================================================

hm27_beta_values = np.load(
    upstream_artifact_paths[
        "phase2.203.final_hm27_methylation_betas"
    ],
    mmap_mode="r",
)

print(
    "HM27 beta matrix shape:",
    hm27_beta_values.shape,
)
print(
    "HM27 sample-axis aligned:",
    hm27_beta_values.shape[1] == len(hm27_sample_index),
)

HM27 beta matrix shape: (24303, 1620)
HM27 sample-axis aligned: True


In [64]:
# =============================================================================
# Extract HM27 beta values for covered CpGs
# =============================================================================

hm27_covered_cpg_index = (
    hm27_covered_fdr_associations[
        ["probe_id", "hm27_matrix_row_index"]
    ]
    .drop_duplicates()
    .sort_values("probe_id")
    .reset_index(drop=True)
)

hm27_row_indices = hm27_covered_cpg_index[
    "hm27_matrix_row_index"
].to_numpy(dtype=np.int64)

hm27_covered_betas = np.asarray(
    hm27_beta_values[hm27_row_indices, :]
)

print(
    "HM27-covered CpGs:",
    len(hm27_covered_cpg_index),
)
print(
    "Extracted HM27 beta matrix:",
    hm27_covered_betas.shape,
)

HM27-covered CpGs: 257
Extracted HM27 beta matrix: (257, 1620)


In [65]:
# =============================================================================
# Check HM27 beta boundaries and missingness
# =============================================================================

finite_hm27_betas = hm27_covered_betas[
    np.isfinite(hm27_covered_betas)
]

print(
    "Missing HM27 beta values:",
    int(np.isnan(hm27_covered_betas).sum()),
)
print(
    "Finite HM27 beta values equal to 0:",
    int(np.equal(finite_hm27_betas, 0.0).sum()),
)
print(
    "Finite HM27 beta values equal to 1:",
    int(np.equal(finite_hm27_betas, 1.0).sum()),
)
print(
    "Finite HM27 beta range:",
    (
        float(finite_hm27_betas.min()),
        float(finite_hm27_betas.max()),
    ),
)

Missing HM27 beta values: 2214
Finite HM27 beta values equal to 0: 0
Finite HM27 beta values equal to 1: 0
Finite HM27 beta range: (0.002576572122052312, 0.9974201917648315)


In [66]:
# =============================================================================
# Transform HM27 beta values to M-values
# =============================================================================

hm27_covered_m_values = np.log2(
    hm27_covered_betas / (1.0 - hm27_covered_betas)
)

print(
    "HM27 M-value matrix:",
    hm27_covered_m_values.shape,
)
print(
    "Missing HM27 M-values:",
    int(np.isnan(hm27_covered_m_values).sum()),
)
print(
    "Finite HM27 M-value range:",
    (
        float(np.nanmin(hm27_covered_m_values)),
        float(np.nanmax(hm27_covered_m_values)),
    ),
)

HM27 M-value matrix: (257, 1620)
Missing HM27 M-values: 2214
Finite HM27 M-value range: (-8.596609115600586, 8.594793319702148)


In [67]:
# =============================================================================
# Align HM27 samples to the frozen RNA expression matrix
# =============================================================================

hm27_rna_column_indices = (
    sample_mapping.loc[
        sample_mapping["hm27_matrix_column_index"].notna(),
        [
            "hm27_matrix_column_index",
            "rna_final_matrix_column_index",
        ],
    ]
    .sort_values("hm27_matrix_column_index")
    ["rna_final_matrix_column_index"]
    .to_numpy(dtype=np.int64)
)

print(
    "HM27-to-RNA correspondences:",
    len(hm27_rna_column_indices),
)
print(
    "Unique RNA columns:",
    np.unique(hm27_rna_column_indices).size,
)
print(
    "RNA column-index range:",
    (
        int(hm27_rna_column_indices.min()),
        int(hm27_rna_column_indices.max()),
    ),
)

HM27-to-RNA correspondences: 1620
Unique RNA columns: 1620
RNA column-index range: (0, 5980)


In [68]:
# =============================================================================
# Extract frozen RNA expression for HM27-covered associations
# =============================================================================

hm27_gene_index = (
    hm27_covered_fdr_associations[
        ["rna_gene_id_base", "resolved_rna_row_index"]
    ]
    .drop_duplicates()
    .sort_values("resolved_rna_row_index")
    .reset_index(drop=True)
)

hm27_rna_row_indices = hm27_gene_index[
    "resolved_rna_row_index"
].to_numpy(dtype=np.int64)

with h5py.File(rna_expression_path, "r") as h5:
    hm27_rna_logcpm = (
        h5["logcpm"][hm27_rna_row_indices, :]
        [:, hm27_rna_column_indices]
    )

print(
    "HM27-covered RNA genes:",
    len(hm27_gene_index),
)
print(
    "Extracted HM27 RNA matrix:",
    hm27_rna_logcpm.shape,
)
print(
    "Missing HM27 RNA values:",
    int(np.isnan(hm27_rna_logcpm).sum()),
)

HM27-covered RNA genes: 255
Extracted HM27 RNA matrix: (255, 1620)
Missing HM27 RNA values: 0


In [69]:
# =============================================================================
# Evaluate lineage-aware HM27 support
# =============================================================================

hm27_cpg_row_lookup = dict(
    zip(
        hm27_covered_cpg_index["probe_id"],
        range(len(hm27_covered_cpg_index)),
    )
)

hm27_gene_row_lookup = dict(
    zip(
        hm27_gene_index["rna_gene_id_base"],
        range(len(hm27_gene_index)),
    )
)

hm27_projects = hm27_sample_index["project_id"].to_numpy()

hm27_support_records = []

for pair in hm27_covered_fdr_associations.itertuples(index=False):
    x = hm27_covered_m_values[
        hm27_cpg_row_lookup[pair.probe_id]
    ]
    y = hm27_rna_logcpm[
        hm27_gene_row_lookup[pair.rna_gene_id_base]
    ]

    complete_mask = np.isfinite(x) & np.isfinite(y)

    supported_projects = []

    for project_id in np.unique(hm27_projects):
        project_mask = (
            complete_mask
            & (hm27_projects == project_id)
        )

        if (
            project_mask.sum() >= 20
            and np.ptp(x[project_mask]) > 0
            and np.ptp(y[project_mask]) > 0
        ):
            supported_projects.append(project_id)

    hm27_support_records.append(
        {
            "probe_id": pair.probe_id,
            "rna_gene_id_base": pair.rna_gene_id_base,
            "n_complete": int(complete_mask.sum()),
            "n_supported_projects": len(supported_projects),
            "hm27_evaluable": len(supported_projects) >= 3,
        }
    )

hm27_support_summary = pd.DataFrame(
    hm27_support_records
)

print(
    "HM27-covered associations:",
    len(hm27_support_summary),
)
print(
    "HM27-evaluable associations:",
    int(hm27_support_summary["hm27_evaluable"].sum()),
)
print(
    "Complete-case range:",
    (
        int(hm27_support_summary["n_complete"].min()),
        int(hm27_support_summary["n_complete"].max()),
    ),
)
print(
    "Supported-project range:",
    (
        int(hm27_support_summary["n_supported_projects"].min()),
        int(hm27_support_summary["n_supported_projects"].max()),
    ),
)

HM27-covered associations: 289
HM27-evaluable associations: 289
Complete-case range: (1543, 1620)
Supported-project range: (10, 10)


In [70]:
# =============================================================================
# Characterize HM27 project-support composition
# =============================================================================

hm27_pair_project_support_records = []

for pair in hm27_covered_fdr_associations.itertuples(index=False):
    x = hm27_covered_m_values[
        hm27_cpg_row_lookup[pair.probe_id]
    ]
    y = hm27_rna_logcpm[
        hm27_gene_row_lookup[pair.rna_gene_id_base]
    ]

    for project_id in np.unique(hm27_projects):
        project_mask = hm27_projects == project_id
        complete_mask = (
            project_mask
            & np.isfinite(x)
            & np.isfinite(y)
        )

        n_complete = int(complete_mask.sum())

        supported = (
            n_complete >= 20
            and np.ptp(x[complete_mask]) > 0
            and np.ptp(y[complete_mask]) > 0
        )

        hm27_pair_project_support_records.append(
            {
                "probe_id": pair.probe_id,
                "rna_gene_id_base": pair.rna_gene_id_base,
                "project_id": project_id,
                "n_complete": n_complete,
                "supported": supported,
            }
        )

hm27_pair_project_support = pd.DataFrame(
    hm27_pair_project_support_records
)

hm27_unsupported_project_summary = (
    hm27_pair_project_support.loc[
        ~hm27_pair_project_support["supported"]
    ]
    .groupby("project_id", as_index=False)
    .agg(
        n_unsupported_pairs=("probe_id", "size"),
        min_complete_cases=("n_complete", "min"),
        max_complete_cases=("n_complete", "max"),
    )
)

print(
    "Distinct supported-project sets:",
    hm27_pair_project_support.loc[
        hm27_pair_project_support["supported"]
    ]
    .groupby(["probe_id", "rna_gene_id_base"])["project_id"]
    .agg(tuple)
    .nunique(),
)

hm27_unsupported_project_summary

Distinct supported-project sets: 1


,project_id,n_unsupported_pairs,min_complete_cases,max_complete_cases
0,TCGA-KIRP,289,5,6


In [72]:
# =============================================================================
# Fit HM27 platform-sensitivity models
# =============================================================================

hm27_supported_projects = (
    hm27_pair_project_support.loc[
        hm27_pair_project_support["supported"],
        "project_id",
    ]
    .drop_duplicates()
    .sort_values()
    .to_numpy()
)

hm27_supported_sample_mask = np.isin(
    hm27_projects,
    hm27_supported_projects,
)

hm27_sensitivity_records = []

for pair in hm27_covered_fdr_associations.itertuples(index=False):
    x_all = hm27_covered_m_values[
        hm27_cpg_row_lookup[pair.probe_id]
    ]
    y_all = hm27_rna_logcpm[
        hm27_gene_row_lookup[pair.rna_gene_id_base]
    ]

    complete_mask = (
        hm27_supported_sample_mask
        & np.isfinite(x_all)
        & np.isfinite(y_all)
    )

    x = x_all[complete_mask]
    y = y_all[complete_mask]
    projects = hm27_projects[complete_mask]

    model_design = pd.get_dummies(
        pd.Categorical(
            projects,
            categories=hm27_supported_projects,
        ),
        drop_first=True,
        dtype=float,
    )
    model_design.insert(0, "intercept", 1.0)
    model_design["cpg_methylation"] = x

    model = sm.OLS(
        y,
        model_design,
    ).fit(cov_type="HC3")

    confidence_interval = model.conf_int().loc[
        "cpg_methylation"
    ]

    hm27_coefficient = float(
        model.params["cpg_methylation"]
    )
    primary_coefficient = float(
        pair.methylation_coefficient
    )

    hm27_sensitivity_records.append(
        {
            "probe_id": pair.probe_id,
            "rna_gene_id_base": pair.rna_gene_id_base,
            "n_complete": int(complete_mask.sum()),
            "n_supported_projects": len(
                hm27_supported_projects
            ),
            "methylation_coefficient": hm27_coefficient,
            "hc3_standard_error": float(
                model.bse["cpg_methylation"]
            ),
            "ci_95_lower": float(
                confidence_interval.iloc[0]
            ),
            "ci_95_upper": float(
                confidence_interval.iloc[1]
            ),
            "direction_preserved": (
                np.sign(hm27_coefficient)
                == np.sign(primary_coefficient)
            ),
            "magnitude_ratio_to_primary": (
                abs(hm27_coefficient)
                / abs(primary_coefficient)
            ),
        }
    )

hm27_sensitivity_results = pd.DataFrame(
    hm27_sensitivity_records
)

print(
    "HM27 sensitivity models:",
    len(hm27_sensitivity_results),
)
print(
    "Complete-case range:",
    (
        int(hm27_sensitivity_results["n_complete"].min()),
        int(hm27_sensitivity_results["n_complete"].max()),
    ),
)
print(
    "Supported projects:",
    int(
        hm27_sensitivity_results[
            "n_supported_projects"
        ].min()
    ),
)
print(
    "Direction preserved:",
    int(
        hm27_sensitivity_results[
            "direction_preserved"
        ].sum()
    ),
)

HM27 sensitivity models: 289
Complete-case range: (1537, 1614)
Supported projects: 10
Direction preserved: 151


In [73]:
# =============================================================================
# Consolidate prespecified sensitivity results
# =============================================================================

association_sensitivities = pd.concat(
    [
        purity_sensitivity_results.assign(
            sensitivity_type="purity",
        ),
        proliferation_sensitivity_results.assign(
            sensitivity_type="proliferation",
        ),
        leukocyte_sensitivity_results.assign(
            sensitivity_type="leukocyte_fraction",
        ),
        hm27_sensitivity_results.assign(
            sensitivity_type="hm27_platform",
        ),
    ],
    ignore_index=True,
)

association_sensitivities = association_sensitivities[
    [
        "probe_id",
        "rna_gene_id_base",
        "sensitivity_type",
        "n_complete",
        "n_supported_projects",
        "methylation_coefficient",
        "hc3_standard_error",
        "ci_95_lower",
        "ci_95_upper",
        "direction_preserved",
        "magnitude_ratio_to_primary",
    ]
]

print(
    "Sensitivity records:",
    len(association_sensitivities),
)

print(
    association_sensitivities
    .groupby("sensitivity_type")
    .agg(
        n_associations=("probe_id", "size"),
        direction_preserved=("direction_preserved", "sum"),
    )
)

Sensitivity records: 972
                    n_associations  direction_preserved
sensitivity_type                                       
hm27_platform                  289                  151
leukocyte_fraction             105                   93
proliferation                  289                  288
purity                         289                  286


In [74]:
# =============================================================================
# Build association-level sensitivity annotations
# =============================================================================

sensitivity_direction_annotations = (
    primary_fdr_associations[
        ["probe_id", "rna_gene_id_base"]
    ]
    .merge(
        purity_sensitivity_results[
            [
                "probe_id",
                "rna_gene_id_base",
                "direction_preserved",
            ]
        ].rename(
            columns={
                "direction_preserved": "purity_direction_preserved",
            }
        ),
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
    .merge(
        proliferation_sensitivity_results[
            [
                "probe_id",
                "rna_gene_id_base",
                "direction_preserved",
            ]
        ].rename(
            columns={
                "direction_preserved": "proliferation_direction_preserved",
            }
        ),
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
    .merge(
        leukocyte_sensitivity_results[
            [
                "probe_id",
                "rna_gene_id_base",
                "direction_preserved",
            ]
        ].rename(
            columns={
                "direction_preserved": "leukocyte_direction_preserved",
            }
        ),
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
    .merge(
        hm27_sensitivity_results[
            [
                "probe_id",
                "rna_gene_id_base",
                "direction_preserved",
            ]
        ].rename(
            columns={
                "direction_preserved": "hm27_direction_preserved",
            }
        ),
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
)

sensitivity_direction_annotations[
    "leukocyte_fraction_applicable"
] = sensitivity_direction_annotations["probe_id"].isin(
    meth_ic128_cpgs
)

print(
    "FDR-supported associations:",
    len(sensitivity_direction_annotations),
)
print(
    "Purity sensitivity available:",
    int(
        sensitivity_direction_annotations[
            "purity_direction_preserved"
        ].notna().sum()
    ),
)
print(
    "Proliferation sensitivity available:",
    int(
        sensitivity_direction_annotations[
            "proliferation_direction_preserved"
        ].notna().sum()
    ),
)
print(
    "Leukocyte sensitivity applicable:",
    int(
        sensitivity_direction_annotations[
            "leukocyte_fraction_applicable"
        ].sum()
    ),
)
print(
    "Leukocyte sensitivity available:",
    int(
        sensitivity_direction_annotations[
            "leukocyte_direction_preserved"
        ].notna().sum()
    ),
)
print(
    "HM27 sensitivity available:",
    int(
        sensitivity_direction_annotations[
            "hm27_direction_preserved"
        ].notna().sum()
    ),
)

FDR-supported associations: 289
Purity sensitivity available: 289
Proliferation sensitivity available: 289
Leukocyte sensitivity applicable: 105
Leukocyte sensitivity available: 105
HM27 sensitivity available: 289


In [75]:
# =============================================================================
# Integrate recurrence and sensitivity evidence
# =============================================================================

fdr_evidence_summary = (
    primary_fdr_characterization
    .merge(
        sensitivity_direction_annotations[
            [
                "probe_id",
                "rna_gene_id_base",
                "purity_direction_preserved",
                "proliferation_direction_preserved",
                "leukocyte_fraction_applicable",
                "leukocyte_direction_preserved",
                "hm27_direction_preserved",
            ]
        ],
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
)

fdr_evidence_summary[
    "promoter_associated_inverse_relationship"
] = (
    fdr_evidence_summary["promoter_associated"]
    & fdr_evidence_summary["methylation_coefficient"].lt(0)
)

print(
    "FDR-supported evidence rows:",
    len(fdr_evidence_summary),
)
print(
    "Cross-project recurrent:",
    int(
        fdr_evidence_summary[
            "cross_project_recurrent"
        ].sum()
    ),
)
print(
    "Promoter-associated inverse:",
    int(
        fdr_evidence_summary[
            "promoter_associated_inverse_relationship"
        ].sum()
    ),
)
print(
    "Recurrent promoter-associated inverse:",
    int(
        (
            fdr_evidence_summary[
                "cross_project_recurrent"
            ]
            & fdr_evidence_summary[
                "promoter_associated_inverse_relationship"
            ]
        ).sum()
    ),
)

FDR-supported evidence rows: 289
Cross-project recurrent: 223
Promoter-associated inverse: 225
Recurrent promoter-associated inverse: 192


In [76]:
# =============================================================================
# Characterize sensitivity stability among recurrent associations
# =============================================================================

recurrent_evidence = (
    fdr_evidence_summary.loc[
        fdr_evidence_summary["cross_project_recurrent"]
    ]
    .copy()
)

recurrent_leukocyte_applicable = recurrent_evidence.loc[
    recurrent_evidence["leukocyte_fraction_applicable"]
]

print(
    "Cross-project recurrent associations:",
    len(recurrent_evidence),
)
print(
    "Purity direction preserved:",
    int(
        recurrent_evidence[
            "purity_direction_preserved"
        ].sum()
    ),
)
print(
    "Proliferation direction preserved:",
    int(
        recurrent_evidence[
            "proliferation_direction_preserved"
        ].sum()
    ),
)
print(
    "Leukocyte-sensitive recurrent associations:",
    len(recurrent_leukocyte_applicable),
)
print(
    "Leukocyte direction preserved:",
    int(
        recurrent_leukocyte_applicable[
            "leukocyte_direction_preserved"
        ].sum()
    ),
)
print(
    "HM27 direction preserved:",
    int(
        recurrent_evidence[
            "hm27_direction_preserved"
        ].sum()
    ),
)

Cross-project recurrent associations: 223
Purity direction preserved: 223
Proliferation direction preserved: 223
Leukocyte-sensitive recurrent associations: 93
Leukocyte direction preserved: 85
HM27 direction preserved: 118


In [77]:
# =============================================================================
# Build the complete primary locus-level evidence table
# =============================================================================

primary_locus_evidence = (
    primary_cpg_gene_family
    .merge(
        primary_model_results,
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
    .merge(
        recurrence_summary[
            [
                "probe_id",
                "rna_gene_id_base",
                "n_same_direction_projects",
                "directional_concordance_fraction",
                "any_lopo_sign_reversal",
                "cross_project_recurrent",
            ]
        ],
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
    .merge(
        sensitivity_direction_annotations[
            [
                "probe_id",
                "rna_gene_id_base",
                "purity_direction_preserved",
                "proliferation_direction_preserved",
                "leukocyte_fraction_applicable",
                "leukocyte_direction_preserved",
                "hm27_direction_preserved",
            ]
        ],
        on=["probe_id", "rna_gene_id_base"],
        how="left",
        validate="one_to_one",
    )
)

primary_locus_evidence["cross_project_recurrent"] = (
    primary_locus_evidence["cross_project_recurrent"]
    .fillna(False)
    .astype(bool)
)

print(
    "Primary CpG-gene pairs:",
    len(primary_locus_evidence),
)
print(
    "FDR-supported:",
    int(
        primary_locus_evidence[
            "primary_fdr_supported"
        ].sum()
    ),
)
print(
    "Not FDR-supported:",
    int(
        (~primary_locus_evidence[
            "primary_fdr_supported"
        ]).sum()
    ),
)
print(
    "Cross-project recurrent:",
    int(
        primary_locus_evidence[
            "cross_project_recurrent"
        ].sum()
    ),
)

Primary CpG-gene pairs: 311
FDR-supported: 289
Not FDR-supported: 22
Cross-project recurrent: 223


In [78]:
# =============================================================================
# Classify primary association direction and promoter context
# =============================================================================

primary_locus_evidence["association_direction"] = np.where(
    primary_locus_evidence["methylation_coefficient"].lt(0),
    "inverse",
    "positive",
)

primary_locus_evidence[
    "promoter_associated_inverse_relationship"
] = (
    primary_locus_evidence["promoter_associated"]
    & primary_locus_evidence["methylation_coefficient"].lt(0)
)

primary_locus_evidence[
    "fdr_supported_promoter_associated_inverse"
] = (
    primary_locus_evidence["primary_fdr_supported"]
    & primary_locus_evidence[
        "promoter_associated_inverse_relationship"
    ]
)

print(
    "Primary inverse associations:",
    int(
        primary_locus_evidence[
            "association_direction"
        ].eq("inverse").sum()
    ),
)
print(
    "Primary positive associations:",
    int(
        primary_locus_evidence[
            "association_direction"
        ].eq("positive").sum()
    ),
)
print(
    "Promoter-associated inverse relationships:",
    int(
        primary_locus_evidence[
            "promoter_associated_inverse_relationship"
        ].sum()
    ),
)
print(
    "FDR-supported promoter-associated inverse:",
    int(
        primary_locus_evidence[
            "fdr_supported_promoter_associated_inverse"
        ].sum()
    ),
)
print(
    "Recurrent promoter-associated inverse:",
    int(
        (
            primary_locus_evidence[
                "cross_project_recurrent"
            ]
            & primary_locus_evidence[
                "promoter_associated_inverse_relationship"
            ]
        ).sum()
    ),
)

Primary inverse associations: 248
Primary positive associations: 63
Promoter-associated inverse relationships: 234
FDR-supported promoter-associated inverse: 225
Recurrent promoter-associated inverse: 192


In [79]:
# =============================================================================
# Attach frozen component and consensus-program context without row expansion
# =============================================================================

cpg_component_context = (
    strong_loading_cpg_memberships
    .assign(
        component_loading_context=lambda df: (
            df["methylation_component"].astype(str)
            + "|"
            + df["loading_tail"].astype(str)
            + "|"
            + df["loading"].astype(str)
        )
    )
    .groupby("probe_id", as_index=False)
    .agg(
        methylation_component_memberships=(
            "methylation_component",
            lambda x: ";".join(sorted(set(x))),
        ),
        component_loading_context=(
            "component_loading_context",
            lambda x: ";".join(sorted(set(x))),
        ),
    )
)

cpg_program_context = (
    strong_loading_cpg_memberships[
        ["probe_id", "methylation_component"]
    ]
    .drop_duplicates()
    .merge(
        methylation_component_context[
            [
                "methylation_component",
                "consensus_program_id",
                "candidate_pair",
                "rna_component",
            ]
        ],
        on="methylation_component",
        how="left",
        validate="many_to_many",
    )
    .assign(
        program_context=lambda df: (
            df["consensus_program_id"].astype(str)
            + "|"
            + df["candidate_pair"].astype(str)
            + "|"
            + df["rna_component"].astype(str)
            + "|"
            + df["methylation_component"].astype(str)
        )
    )
    .groupby("probe_id", as_index=False)
    .agg(
        consensus_program_memberships=(
            "consensus_program_id",
            lambda x: ";".join(sorted(set(x))),
        ),
        program_context=(
            "program_context",
            lambda x: ";".join(sorted(set(x))),
        ),
    )
)

primary_locus_evidence = (
    primary_locus_evidence
    .merge(
        cpg_component_context,
        on="probe_id",
        how="left",
        validate="many_to_one",
    )
    .merge(
        cpg_program_context,
        on="probe_id",
        how="left",
        validate="many_to_one",
    )
)

print(
    "Primary evidence rows:",
    len(primary_locus_evidence),
)
print(
    "Rows with component context:",
    int(
        primary_locus_evidence[
            "methylation_component_memberships"
        ].notna().sum()
    ),
)
print(
    "Rows with consensus-program context:",
    int(
        primary_locus_evidence[
            "consensus_program_memberships"
        ].notna().sum()
    ),
)
print(
    "Unique CpG-gene pairs:",
    primary_locus_evidence[
        ["probe_id", "rna_gene_id_base"]
    ].drop_duplicates().shape[0],
)

Primary evidence rows: 311
Rows with component context: 311
Rows with consensus-program context: 311
Unique CpG-gene pairs: 311


In [80]:
# =============================================================================
# Build CpG-gene annotation and primary-eligibility table
# =============================================================================

cpg_gene_annotation_eligibility = (
    cpg_gene_harmonization
    .copy()
)

primary_pair_keys = set(
    zip(
        primary_cpg_gene_family["probe_id"],
        primary_cpg_gene_family["rna_gene_id_base"],
    )
)

cpg_gene_annotation_eligibility["primary_eligible"] = [
    (
        probe_id,
        rna_gene_id_base,
    ) in primary_pair_keys
    if pd.notna(rna_gene_id_base)
    else False
    for probe_id, rna_gene_id_base in zip(
        cpg_gene_annotation_eligibility["probe_id"],
        cpg_gene_annotation_eligibility["rna_gene_id_base"],
    )
]

cpg_gene_annotation_eligibility["exclusion_reason"] = np.where(
    cpg_gene_annotation_eligibility["primary_eligible"],
    pd.NA,
    "unresolved_not_in_frozen_rna_axis",
)

print(
    "Annotated CpG-gene pairs:",
    len(cpg_gene_annotation_eligibility),
)
print(
    "Primary eligible:",
    int(
        cpg_gene_annotation_eligibility[
            "primary_eligible"
        ].sum()
    ),
)
print(
    "Excluded:",
    int(
        (~cpg_gene_annotation_eligibility[
            "primary_eligible"
        ]).sum()
    ),
)
print(
    cpg_gene_annotation_eligibility[
        "exclusion_reason"
    ].value_counts(dropna=False)
)

Annotated CpG-gene pairs: 336
Primary eligible: 311
Excluded: 25
exclusion_reason
NaN                                  311
unresolved_not_in_frozen_rna_axis     25
Name: count, dtype: int64


In [81]:
# =============================================================================
# Inspect strong-CpG annotation coverage schema
# =============================================================================

print(
    "Strong-CpG annotation coverage columns:",
    strong_cpg_annotation_coverage.columns.tolist(),
)

Strong-CpG annotation coverage columns: ['probe_id', 'model_matrix_row_index', 'n_methylation_components', 'methylation_components', 'component_tail_memberships', 'cpg_chr', 'cpg_start', 'cpg_end', 'n_protein_coding_genes', 'n_promoter_genes', 'n_transcript_genes', 'promoter_associated', 'transcript_associated', 'annotation_status']


In [82]:
# =============================================================================
# Add strong-loading CpGs without protein-coding gene mappings
# =============================================================================

unmapped_strong_cpg_rows = (
    strong_cpg_annotation_coverage.loc[
        strong_cpg_annotation_coverage[
            "n_protein_coding_genes"
        ].eq(0)
    ]
    .reindex(
        columns=cpg_gene_annotation_eligibility.columns
    )
    .copy()
)

unmapped_strong_cpg_rows["primary_eligible"] = False
unmapped_strong_cpg_rows[
    "exclusion_reason"
] = "no_protein_coding_gene_mapping"

cpg_gene_annotation_eligibility_complete = (
    pd.concat(
        [
            cpg_gene_annotation_eligibility,
            unmapped_strong_cpg_rows,
        ],
        ignore_index=True,
    )
)

print(
    "Eligibility records:",
    len(cpg_gene_annotation_eligibility_complete),
)
print(
    "Primary eligible:",
    int(
        cpg_gene_annotation_eligibility_complete[
            "primary_eligible"
        ].sum()
    ),
)
print(
    "Excluded:",
    int(
        (~cpg_gene_annotation_eligibility_complete[
            "primary_eligible"
        ]).sum()
    ),
)
print(
    cpg_gene_annotation_eligibility_complete[
        "exclusion_reason"
    ].value_counts(dropna=False)
)

Eligibility records: 343
Primary eligible: 311
Excluded: 32
exclusion_reason
NaN                                  311
unresolved_not_in_frozen_rna_axis     25
no_protein_coding_gene_mapping         7
Name: count, dtype: int64


In [83]:
# =============================================================================
# Characterize locus-level evidence by methylation component
# =============================================================================

component_evidence = (
    primary_locus_evidence[
        [
            "probe_id",
            "rna_gene_id_base",
            "primary_fdr_supported",
            "cross_project_recurrent",
            "fdr_supported_promoter_associated_inverse",
        ]
    ]
    .merge(
        strong_loading_cpg_memberships[
            [
                "probe_id",
                "methylation_component",
            ]
        ].drop_duplicates(),
        on="probe_id",
        how="left",
        validate="many_to_many",
    )
    .drop_duplicates(
        [
            "probe_id",
            "rna_gene_id_base",
            "methylation_component",
        ]
    )
)

component_evidence_summary = (
    component_evidence
    .groupby(
        "methylation_component",
        as_index=False,
    )
    .agg(
        n_primary_pairs=("probe_id", "size"),
        n_fdr_supported=("primary_fdr_supported", "sum"),
        n_cross_project_recurrent=("cross_project_recurrent", "sum"),
        n_fdr_promoter_inverse=(
            "fdr_supported_promoter_associated_inverse",
            "sum",
        ),
    )
)

component_evidence_summary

,methylation_component,n_primary_pairs,n_fdr_supported,n_cross_project_recurrent,n_fdr_promoter_inverse
0,METH_IC050,111,100,78,82
1,METH_IC128,111,105,93,93
2,METH_IC169,110,103,68,65


In [85]:
# =============================================================================
# Characterize sensitivity stability by methylation component
# =============================================================================

recurrent_component_sensitivity = (
    recurrent_evidence[
        [
            "probe_id",
            "rna_gene_id_base",
            "purity_direction_preserved",
            "proliferation_direction_preserved",
            "leukocyte_direction_preserved",
            "hm27_direction_preserved",
        ]
    ]
    .merge(
        strong_loading_cpg_memberships[
            ["probe_id", "methylation_component"]
        ].drop_duplicates(),
        on="probe_id",
        how="left",
        validate="many_to_many",
    )
    .drop_duplicates(
        [
            "probe_id",
            "rna_gene_id_base",
            "methylation_component",
        ]
    )
)

recurrent_component_sensitivity[
    "leukocyte_applicable_in_component"
] = recurrent_component_sensitivity[
    "methylation_component"
].eq("METH_IC128")

recurrent_component_sensitivity[
    "leukocyte_preserved_in_component"
] = (
    recurrent_component_sensitivity[
        "leukocyte_applicable_in_component"
    ]
    & recurrent_component_sensitivity[
        "leukocyte_direction_preserved"
    ].fillna(False)
)

component_sensitivity_summary = (
    recurrent_component_sensitivity
    .groupby("methylation_component", as_index=False)
    .agg(
        n_recurrent=("probe_id", "size"),
        n_purity_preserved=("purity_direction_preserved", "sum"),
        n_proliferation_preserved=(
            "proliferation_direction_preserved",
            "sum",
        ),
        n_leukocyte_applicable=(
            "leukocyte_applicable_in_component",
            "sum",
        ),
        n_leukocyte_preserved=(
            "leukocyte_preserved_in_component",
            "sum",
        ),
        n_hm27_preserved=("hm27_direction_preserved", "sum"),
    )
)

component_sensitivity_summary

,methylation_component,n_recurrent,n_purity_preserved,n_proliferation_preserved,n_leukocyte_applicable,n_leukocyte_preserved,n_hm27_preserved
0,METH_IC050,78,78,78,0,0,36
1,METH_IC128,93,93,93,93,85,53
2,METH_IC169,68,68,68,0,0,35


In [87]:
# =============================================================================
# Characterize recurrent promoter-associated inverse relationships by component
# =============================================================================

recurrent_regulatory_component = (
    primary_locus_evidence.loc[
        primary_locus_evidence[
            "cross_project_recurrent"
        ],
        [
            "probe_id",
            "rna_gene_id_base",
            "promoter_associated_inverse_relationship",
        ],
    ]
    .merge(
        strong_loading_cpg_memberships[
            ["probe_id", "methylation_component"]
        ].drop_duplicates(),
        on="probe_id",
        how="left",
        validate="many_to_many",
    )
    .drop_duplicates(
        [
            "probe_id",
            "rna_gene_id_base",
            "methylation_component",
        ]
    )
)

recurrent_regulatory_component_summary = (
    recurrent_regulatory_component
    .groupby("methylation_component", as_index=False)
    .agg(
        n_recurrent=("probe_id", "size"),
        n_recurrent_promoter_inverse=(
            "promoter_associated_inverse_relationship",
            "sum",
        ),
    )
)

recurrent_regulatory_component_summary[
    "promoter_inverse_fraction"
] = (
    recurrent_regulatory_component_summary[
        "n_recurrent_promoter_inverse"
    ]
    / recurrent_regulatory_component_summary[
        "n_recurrent"
    ]
)

recurrent_regulatory_component_summary

,methylation_component,n_recurrent,n_recurrent_promoter_inverse,promoter_inverse_fraction
0,METH_IC050,78,72,0.923077
1,METH_IC128,93,86,0.924731
2,METH_IC169,68,48,0.705882


In [89]:
# =============================================================================
# Finalize CpG-gene annotation and eligibility output
# =============================================================================

cpg_gene_annotation_eligibility_output = (
    cpg_gene_annotation_eligibility_complete
    .merge(
        cpg_component_context,
        on="probe_id",
        how="left",
        validate="many_to_one",
    )
    .merge(
        cpg_program_context,
        on="probe_id",
        how="left",
        validate="many_to_one",
    )
    .sort_values(
        [
            "primary_eligible",
            "probe_id",
            "rna_gene_id_base",
        ],
        ascending=[False, True, True],
        na_position="last",
    )
    .reset_index(drop=True)
)

print(
    "Final eligibility output:",
    cpg_gene_annotation_eligibility_output.shape,
)

Final eligibility output: (343, 29)


In [91]:
# =============================================================================
# Prepare the primary CpG-gene association output
# =============================================================================

primary_cpg_gene_associations_output = (
    primary_locus_evidence
    .drop(
        columns=[
            "n_same_direction_projects",
            "directional_concordance_fraction",
            "any_lopo_sign_reversal",
            "cross_project_recurrent",
            "purity_direction_preserved",
            "proliferation_direction_preserved",
            "leukocyte_fraction_applicable",
            "leukocyte_direction_preserved",
            "hm27_direction_preserved",
        ]
    )
    .sort_values(
        ["probe_id", "rna_gene_id_base"]
    )
    .reset_index(drop=True)
)

print(
    "Primary association output:",
    primary_cpg_gene_associations_output.shape,
)

Primary association output: (311, 43)


In [92]:
# =============================================================================
# Persist final notebook-451 tabular outputs
# =============================================================================

output_dir = Paths.secondary_characterization
output_dir.mkdir(parents=True, exist_ok=True)

output_paths = {
    "annotation_eligibility": (
        output_dir
        / "451_cpg_gene_annotation_eligibility.csv"
    ),
    "primary_associations": (
        output_dir
        / "451_primary_cpg_gene_associations.csv"
    ),
    "within_project": (
        output_dir
        / "451_within_project_cpg_gene_associations.csv"
    ),
    "lopo": (
        output_dir
        / "451_leave_one_project_out_associations.csv"
    ),
    "sensitivities": (
        output_dir
        / "451_association_sensitivities.csv"
    ),
    "final_evidence": (
        output_dir
        / "451_locus_level_methylation_expression_evidence.csv"
    ),
}

cpg_gene_annotation_eligibility_output.to_csv(
    output_paths["annotation_eligibility"],
    index=False,
)

primary_cpg_gene_associations_output.to_csv(
    output_paths["primary_associations"],
    index=False,
)

within_project_results.sort_values(
    ["probe_id", "rna_gene_id_base", "project_id"]
).to_csv(
    output_paths["within_project"],
    index=False,
)

lopo_results.sort_values(
    ["probe_id", "rna_gene_id_base", "omitted_project_id"]
).to_csv(
    output_paths["lopo"],
    index=False,
)

association_sensitivities.sort_values(
    ["probe_id", "rna_gene_id_base", "sensitivity_type"]
).to_csv(
    output_paths["sensitivities"],
    index=False,
)

primary_locus_evidence.sort_values(
    ["probe_id", "rna_gene_id_base"]
).to_csv(
    output_paths["final_evidence"],
    index=False,
)

for artifact_name, path in output_paths.items():
    print(
        f"{artifact_name}: "
        f"{project_relative_path(path)}"
    )

annotation_eligibility: data/processed/secondary_characterization/451_cpg_gene_annotation_eligibility.csv
primary_associations: data/processed/secondary_characterization/451_primary_cpg_gene_associations.csv
within_project: data/processed/secondary_characterization/451_within_project_cpg_gene_associations.csv
lopo: data/processed/secondary_characterization/451_leave_one_project_out_associations.csv
sensitivities: data/processed/secondary_characterization/451_association_sensitivities.csv
final_evidence: data/processed/secondary_characterization/451_locus_level_methylation_expression_evidence.csv


In [93]:
# =============================================================================
# Persist notebook-451 analysis metadata
# =============================================================================

output_objects = {
    "annotation_eligibility": cpg_gene_annotation_eligibility_output,
    "primary_associations": primary_cpg_gene_associations_output,
    "within_project": within_project_results,
    "lopo": lopo_results,
    "sensitivities": association_sensitivities,
    "final_evidence": primary_locus_evidence,
}

analysis_metadata = {
    "notebook": (
        "451_locus_level_methylation_expression_characterization.ipynb"
    ),
    "run_timestamp_utc": pd.Timestamp.now(tz="UTC").isoformat(),
    "upstream_artifacts": {
        artifact_id: {
            "path": project_relative_path(
                upstream_artifact_paths[artifact_id]
            ),
            "sha256": artifact_registry["artifacts"][
                artifact_id
            ]["sha256"],
        }
        for artifact_id in UPSTREAM_ARTIFACT_IDS
    },
    "cpg_annotation": CPG_ANNOTATION_SPEC,
    "strong_loading_rule": {
        "negative_tail_per_component": 50,
        "positive_tail_per_component": 50,
        "components": [
            "METH_IC050",
            "METH_IC128",
            "METH_IC169",
        ],
    },
    "primary_support": {
        "minimum_complete_cases_per_project": 20,
        "require_nonzero_methylation_variation": True,
        "require_nonzero_expression_variation": True,
        "minimum_supported_projects_per_pair": 3,
    },
    "primary_model": (
        "gene_expression ~ CpG_methylation + C(project_id)"
    ),
    "methylation_scale": "M-value",
    "uncertainty_estimator": "HC3",
    "multiple_testing": {
        "method": "Benjamini-Hochberg",
        "family_size": 311,
        "fdr_threshold": 0.05,
    },
    "recurrence_criteria": {
        "primary_fdr_supported": True,
        "minimum_supported_projects": 3,
        "minimum_same_direction_projects": 3,
        "minimum_directional_concordance": 0.70,
        "require_no_lopo_sign_reversal": True,
    },
    "sensitivities": {
        "purity": (
            "gene_expression ~ CpG_methylation "
            "+ absolute_purity + C(project_id)"
        ),
        "proliferation": (
            "gene_expression ~ CpG_methylation "
            "+ external_panimmune_proliferation_score "
            "+ C(project_id)"
        ),
        "leukocyte_fraction": {
            "scope": "METH_IC128 primary FDR-supported associations",
            "model": (
                "gene_expression ~ CpG_methylation "
                "+ leukocyte_fraction + C(project_id)"
            ),
        },
        "hm27_platform": {
            "role": "cross-platform sensitivity",
            "minimum_complete_cases_per_project": 20,
            "minimum_supported_projects_per_pair": 3,
            "independent_biological_validation": False,
        },
    },
    "outputs": {
        name: {
            "path": project_relative_path(output_paths[name]),
            "shape": list(output_objects[name].shape),
            "sha256": calculate_sha256(output_paths[name]),
        }
        for name in output_paths
    },
    "analytical_limitations": [
        "Associations do not establish causal methylation-mediated regulation.",
        "Cross-project recurrence does not establish biological universality across cancers.",
        "HM27 is a platform-sensitivity analysis, not independent biological validation.",
        "METH_IC128 retains upstream cellularity and immune-composition interpretive concerns.",
        "The inferential family is restricted to prespecified strong-loading loci and is not genome-wide.",
    ],
}

metadata_path = (
    output_dir
    / "451_analysis_metadata.json"
)

with metadata_path.open("w", encoding="utf-8") as handle:
    json.dump(
        analysis_metadata,
        handle,
        indent=2,
        sort_keys=True,
    )
    handle.write("\n")

print(
    "analysis_metadata:",
    project_relative_path(metadata_path),
)

analysis_metadata: data/processed/secondary_characterization/451_analysis_metadata.json


In [94]:
# =============================================================================
# Register frozen notebook-451 artifacts
# =============================================================================

from pancancer_epigenetics.utils.artifact_registry import (
    load_artifact_registry,
    validate_artifact_registry,
)

notebook_path = (
    "notebooks/phase4b_secondary_molecular_characterization/"
    "451_locus_level_methylation_expression_characterization.ipynb"
)

annotation_raw_ref = (
    "/tcga/external_resources/sesame_hm450_hg38_annotation"
)

artifact_specs = {
    "phase4b.451.cpg_gene_annotation_eligibility": {
        "path": output_paths["annotation_eligibility"],
        "role": "handoff",
        "shape": list(cpg_gene_annotation_eligibility_output.shape),
        "inputs": [
            {"type": "raw_registry", "ref": annotation_raw_ref},
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_probe_mapping",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.205.rna_program_discovery_expression",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.205.methylation_candidate_probe_loadings",
            },
            {
                "type": "artifact",
                "artifact_id": "phase4.401.consensus_transcriptomic_program_catalog",
            },
            {
                "type": "artifact",
                "artifact_id": "phase4.401.consensus_tumor_arm_context",
            },
        ],
    },
    "phase4b.451.primary_cpg_gene_associations": {
        "path": output_paths["primary_associations"],
        "role": "handoff",
        "shape": list(primary_cpg_gene_associations_output.shape),
        "inputs": [
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.cpg_gene_annotation_eligibility",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_sample_mapping",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_hm450_methylation_betas",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.205.rna_program_discovery_expression",
            },
        ],
    },
    "phase4b.451.within_project_cpg_gene_associations": {
        "path": output_paths["within_project"],
        "role": "handoff",
        "shape": list(within_project_results.shape),
        "inputs": [
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.primary_cpg_gene_associations",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_sample_mapping",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_hm450_methylation_betas",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.205.rna_program_discovery_expression",
            },
        ],
    },
    "phase4b.451.leave_one_project_out_associations": {
        "path": output_paths["lopo"],
        "role": "handoff",
        "shape": list(lopo_results.shape),
        "inputs": [
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.primary_cpg_gene_associations",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_sample_mapping",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_hm450_methylation_betas",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.205.rna_program_discovery_expression",
            },
        ],
    },
    "phase4b.451.association_sensitivities": {
        "path": output_paths["sensitivities"],
        "role": "handoff",
        "shape": list(association_sensitivities.shape),
        "inputs": [
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.primary_cpg_gene_associations",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_sample_mapping",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_hm450_methylation_betas",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.203.final_hm27_methylation_betas",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.204.confounder_covariates",
            },
            {
                "type": "artifact",
                "artifact_id": "phase2.205.rna_program_discovery_expression",
            },
        ],
    },
    "phase4b.451.locus_level_methylation_expression_evidence": {
        "path": output_paths["final_evidence"],
        "role": "handoff",
        "shape": list(primary_locus_evidence.shape),
        "inputs": [
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.cpg_gene_annotation_eligibility",
            },
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.primary_cpg_gene_associations",
            },
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.within_project_cpg_gene_associations",
            },
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.leave_one_project_out_associations",
            },
            {
                "type": "artifact",
                "artifact_id": "phase4b.451.association_sensitivities",
            },
        ],
    },
    "phase4b.451.analysis_metadata": {
        "path": metadata_path,
        "role": "metadata",
        "shape": None,
        "inputs": [
            {
                "type": "artifact",
                "artifact_id": artifact_id,
            }
            for artifact_id in [
                "phase4b.451.cpg_gene_annotation_eligibility",
                "phase4b.451.primary_cpg_gene_associations",
                "phase4b.451.within_project_cpg_gene_associations",
                "phase4b.451.leave_one_project_out_associations",
                "phase4b.451.association_sensitivities",
                "phase4b.451.locus_level_methylation_expression_evidence",
            ]
        ],
    },
}

artifact_registry = load_artifact_registry()

for artifact_id, spec in artifact_specs.items():
    artifact_registry["artifacts"][artifact_id] = {
        "path": project_relative_path(spec["path"]),
        "phase": 4,
        "status": "frozen",
        "artifact_role": spec["role"],
        "producer": {
            "type": "notebook",
            "path": notebook_path,
        },
        "shape": spec["shape"],
        "size_bytes": spec["path"].stat().st_size,
        "sha256": calculate_sha256(spec["path"]),
        "inputs": spec["inputs"],
    }

validate_artifact_registry(artifact_registry)

with Paths.artifact_registry.open(
    "w",
    encoding="utf-8",
) as handle:
    json.dump(
        artifact_registry,
        handle,
        indent=2,
    )
    handle.write("\n")

print(
    "Registered notebook-451 artifacts:",
    len(artifact_specs),
)

Registered notebook-451 artifacts: 7


## Results summary and interpretation

Notebook 451 evaluated locus-level methylation–expression relationships within
the prespecified strong-loading CpG context of `METH_IC050`, `METH_IC128`, and
`METH_IC169`.

The frozen strong-loading universe contained 279 unique CpGs. All were covered
by the frozen HM450 hg38 annotation; 272 had at least one protein-coding gene
mapping and 7 had no protein-coding gene mapping. Biological annotation yielded
336 unique CpG–gene pairs, of which 311 mapped deterministically to the frozen
RNA-seq feature axis and entered the complete primary inferential family.
Twenty-five annotated CpG–gene mappings remained unresolved in the frozen RNA
representation and were not rescued.

Primary HM450 models adjusted for TCGA project and used HC3 uncertainty.
Benjamini–Hochberg correction was applied globally across the 311 prespecified
CpG–gene tests. Of these, 289 were FDR-supported at q < 0.05.

Among the FDR-supported associations, 223 satisfied the prespecified
cross-project recurrence criteria, combining directional concordance across
supported TCGA projects with leave-one-project-out sign stability. Of the 223
recurrent associations, 195 were inverse and 28 were positive. A total of 192
recurrent associations were both promoter-associated and inverse, representing
relationships compatible with an epigenetic regulatory hypothesis but not
evidence of methylation-mediated transcriptional repression or causality.

Contextual characterization showed that recurrent evidence was represented
across all three frozen methylation components. Recurrent promoter-associated
inverse relationships accounted for 72/78 contextual recurrent associations in
`METH_IC050`, 86/93 in `METH_IC128`, and 48/68 in `METH_IC169`. Because CpGs can
belong to more than one methylation-component or consensus-program context,
these component-specific counts are overlapping contextual annotations and are
not independent inferential families.

Direction was preserved for all 223 recurrent associations in both the tumor
purity and proliferation sensitivity analyses. Within the prespecified
`METH_IC128` cellular-composition sensitivity, 85/93 recurrent associations
preserved direction after adjustment for leukocyte fraction. This does not
remove the upstream cellularity/immune-composition limitation attached to
`METH_IC128`.

HM27 platform sensitivity was substantially less concordant: 118/223 recurrent
HM450 associations preserved direction in the HM27 analysis. HM27 therefore
provides limited cross-platform compatibility rather than independent
biological validation. Differences in platform coverage, sample composition,
and represented TCGA lineages prevent attribution of this discordance to
platform effects alone.

These results characterize recurrent locus-level molecular associations within
a deliberately selected strong-loading methylation context. The high fraction
of FDR-supported associations must not be interpreted as a genome-wide hit
rate, and cross-project recurrence must not be interpreted as biological
universality across cancers.

Notebook 451 does not establish causal epigenetic regulation, a mechanism of
drug resistance, a clinical predictor, a validated biomarker, or a validated
therapeutic target. The resulting CpG–gene relationships constitute secondary
molecular context for the frozen consensus programs and are intended for
downstream integration with independent functional and pharmacogenomic
evidence.